// Grant Discovery Configuration for Sacred Foundation
// Keywords and sources for finding relevant grants

export const sacredKeywords = {
  // Primary focus areas - directly from Sacred Bible
  primary: [
    'cacao',
    'ceremonial cacao',
    'criollo',
    'heirloom cacao',
    'indigenous',
    'indigenous communities',
    'indigenous peoples',
    'ceremony',
    'traditional knowledge',
    'ancestral wisdom',
    'sacred plants',
    'plant medicine',
    'native communities',
    'first nations',
    'aboriginal',
    'tribal communities',
    'ashaninka',
    'maya',
    'aztec',
  ],

  // Secondary relevance - from Sacred's Theory of Change
  secondary: [
    // Sustainability & Environment
    'sustainability',
    'regenerative agriculture',
    'regenerative farming',
    'agroforestry',
    'permaculture',
    'deforestation',
    'rainforest preservation',
    'amazon protection',
    'forest conservation',
    'climate action',
    'biodiversity',

    // Food & Trade
    'food systems',
    'food sovereignty',
    'fair trade',
    'direct trade',
    'ethical sourcing',
    'supply chain transparency',
    'smallholder farmers',
    'small-scale farmers',
    'artisanal',
    'premium food',
    'chocolate',
    'cocoa',

    // Mental Health & Wellbeing (loneliness epidemic)
    'wellbeing',
    'mental health',
    'mental wellness',
    'loneliness',
    'social connection',
    'community building',
    'social isolation',
    'holistic health',
    'mindfulness',

    // Alcohol alternatives (sober curious movement)
    'alcohol alternative',
    'non-alcoholic',
    'sober curious',
    'mindful drinking',
    'functional beverage',

    // Cultural & Heritage
    'cultural preservation',
    'cultural heritage',
    'intangible heritage',
    'traditional practices',
    'ancestral knowledge',

    // Social Enterprise
    'social enterprise',
    'social entrepreneurship',
    'impact investing',
    'community development',
    'cooperative',
    'B Corp',

    // Land Rights
    'land rights',
    'indigenous sovereignty',
    'territorial rights',
  ],

  // Geographic focus
  geographic: [
    'Peru',
    'Peruvian',
    'Latin America',
    'South America',
    'Central America',
    'Andes',
    'Andean',
    'Amazon',
    'Amazonian',
    'Australia',
    'Australian',
    'Netherlands',
    'Dutch',
    'Holland',
    'Europe',
    'European',
    'Global South',
    'Ecuador',
    'Colombia',
    'Bolivia',
    'Guatemala',
    'Mexico',
    'Indonesia',
    'West Africa',
    'Ghana',
    'Ivory Coast',
  ],

  // Negative keywords (exclude grants mentioning these)
  exclude: [
    'fossil fuel',
    'oil and gas',
    'mining extraction',
    'tobacco',
    'gambling',
    'weapons',
    'military',
  ]
}

// Scoring weights
export const relevanceWeights = {
  primaryKeyword: 30,      // Points per primary keyword match
  secondaryKeyword: 15,    // Points per secondary keyword match
  geographicMatch: 20,     // Points per geographic match
  excludeKeyword: -100,    // Penalty for excluded keywords
  amountBonus: {           // Bonus based on grant amount
    small: 5,              // < €10k
    medium: 10,            // €10k - €50k
    large: 15,             // €50k - €200k
    major: 20,             // > €200k
  },
  deadlineBonus: {
    urgent: 10,            // < 30 days
    soon: 5,               // 30-90 days
  }
}

// Minimum score to show a discovered grant (lowered to catch more potential grants)
export const minimumRelevanceScore = 5

// Grant databases and sources to scrape
export const grantSources = [
  // Australian Sources
  {
    id: 'grants-gov-au',
    name: 'Grants.gov.au',
    url: 'https://www.grants.gov.au/',
    searchUrl: 'https://www.grants.gov.au/Search/SearchGrant',
    type: 'government',
    region: 'Australia',
    categories: ['all'],
    scrapeMethod: 'api', // Has API
    enabled: true,
  },
  {
    id: 'business-gov-au',
    name: 'Business.gov.au Grants Finder',
    url: 'https://business.gov.au/grants-and-programs',
    type: 'government',
    region: 'Australia',
    categories: ['business', 'innovation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'philanthropy-aus',
    name: 'Philanthropy Australia',
    url: 'https://www.philanthropy.org.au/tools-resources/funding-opportunities/',
    type: 'foundation',
    region: 'Australia',
    categories: ['social', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // Dutch/European Sources
  {
    id: 'cultuurfonds',
    name: 'Prins Bernhard Cultuurfonds',
    url: 'https://www.cultuurfonds.nl/aanvragen',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['culture', 'heritage'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'doen-foundation',
    name: 'DOEN Foundation',
    url: 'https://www.doen.nl/en/what-we-do',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['sustainability', 'culture', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'oranje-fonds',
    name: 'Oranje Fonds',
    url: 'https://www.oranjefonds.nl/aanvragen',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['social', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'nwo',
    name: 'NWO - Dutch Research Council',
    url: 'https://www.nwo.nl/en/calls',
    type: 'government',
    region: 'Netherlands',
    categories: ['research', 'innovation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'creative-europe',
    name: 'Creative Europe',
    url: 'https://culture.ec.europa.eu/funding',
    type: 'government',
    region: 'Europe',
    categories: ['culture', 'creative'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'horizon-europe',
    name: 'Horizon Europe',
    url: 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/',
    type: 'government',
    region: 'Europe',
    categories: ['research', 'innovation', 'sustainability'],
    scrapeMethod: 'api',
    enabled: true,
  },

  // International/Global Sources
  {
    id: 'global-giving',
    name: 'GlobalGiving',
    url: 'https://www.globalgiving.org/grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['social', 'community', 'environment'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'ashoka',
    name: 'Ashoka Fellowships',
    url: 'https://www.ashoka.org/en/our-network/ashoka-fellows',
    type: 'foundation',
    region: 'Global',
    categories: ['social enterprise', 'innovation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'skoll',
    name: 'Skoll Foundation',
    url: 'https://skoll.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['social enterprise', 'impact'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'echoing-green',
    name: 'Echoing Green',
    url: 'https://echoinggreen.org/fellowship/',
    type: 'foundation',
    region: 'Global',
    categories: ['social enterprise', 'leadership'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'patagonia-env',
    name: 'Patagonia Environmental Grants',
    url: 'https://www.patagonia.com/how-we-fund/',
    type: 'corporate',
    region: 'Global',
    categories: ['environment', 'sustainability'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'ben-jerry',
    name: 'Ben & Jerry\'s Foundation',
    url: 'https://benandjerrysfoundation.org/the-grassroots-organizing-for-social-change-program/',
    type: 'corporate',
    region: 'Global',
    categories: ['social', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // Food & Agriculture Specific
  {
    id: 'slow-food',
    name: 'Slow Food Foundation',
    url: 'https://www.fondazioneslowfood.com/en/what-we-do/',
    type: 'foundation',
    region: 'Global',
    categories: ['food', 'sustainability', 'indigenous'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'agrifood-atlas',
    name: 'Agrifood Atlas',
    url: 'https://www.boell.de/en/agrifood-atlas',
    type: 'foundation',
    region: 'Global',
    categories: ['food', 'agriculture'],
    scrapeMethod: 'html',
    enabled: false, // Info resource, not grants
  },
  {
    id: 'christensen-fund',
    name: 'The Christensen Fund',
    url: 'https://www.christensenfund.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'biodiversity', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'swift-foundation',
    name: 'Swift Foundation',
    url: 'https://swiftfoundation.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'environment', 'rights'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // Indigenous & Cultural Preservation
  {
    id: 'first-peoples',
    name: 'First Peoples Worldwide',
    url: 'https://www.firstpeoplesworldwide.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'rights'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'cultural-survival',
    name: 'Cultural Survival',
    url: 'https://www.culturalsurvival.org/grants',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'culture', 'media'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // Aggregator Sites
  {
    id: 'funds-for-ngos',
    name: 'Funds for NGOs',
    url: 'https://www2.fundsforngos.org/',
    type: 'aggregator',
    region: 'Global',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'candid',
    name: 'Candid (Foundation Directory)',
    url: 'https://candid.org/find-funding',
    type: 'aggregator',
    region: 'Global',
    categories: ['all'],
    scrapeMethod: 'api',
    enabled: false, // Requires subscription
  },

  // ===== ADDITIONAL DUTCH FOUNDATIONS =====
  {
    id: 'vsbfonds',
    name: 'VSBfonds',
    url: 'https://www.vsbfonds.nl/aanvragen',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['culture', 'social', 'education'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'adessium',
    name: 'Adessium Foundation',
    url: 'https://www.adessium.org/what-we-support/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['sustainability', 'social', 'journalism'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'triodos-foundation',
    name: 'Triodos Foundation',
    url: 'https://www.triodos.nl/triodos-foundation',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['sustainability', 'culture', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'iona-stichting',
    name: 'Iona Stichting',
    url: 'https://www.ionastichting.nl/aanvragen/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['culture', 'spirituality', 'education'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'haella-stichting',
    name: 'Haëlla Stichting',
    url: 'https://www.haella.nl/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['development', 'social', 'sustainability'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'stichting-democratie-media',
    name: 'Stichting Democratie en Media',
    url: 'https://www.democratieenmedia.nl/subsidies/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['media', 'democracy', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'mondriaan-fonds',
    name: 'Mondriaan Fonds',
    url: 'https://www.mondriaanfonds.nl/aanvragen/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'art', 'heritage'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'fonds21',
    name: 'Fonds 21',
    url: 'https://www.fonds21.nl/aanvragen',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['culture', 'youth', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== MAJOR GLOBAL FOUNDATIONS =====
  {
    id: 'ford-foundation',
    name: 'Ford Foundation',
    url: 'https://www.fordfoundation.org/work/our-grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'rights', 'equality', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'open-society',
    name: 'Open Society Foundations',
    url: 'https://www.opensocietyfoundations.org/grants',
    type: 'foundation',
    region: 'Global',
    categories: ['rights', 'justice', 'democracy', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'packard-foundation',
    name: 'David and Lucile Packard Foundation',
    url: 'https://www.packard.org/grants-and-investments/',
    type: 'foundation',
    region: 'Global',
    categories: ['environment', 'sustainability', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: '11th-hour-project',
    name: '11th Hour Project',
    url: 'https://11thhourproject.org/grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['environment', 'food', 'sustainability'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'hewlett-foundation',
    name: 'William and Flora Hewlett Foundation',
    url: 'https://hewlett.org/grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['environment', 'education', 'democracy'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'macarthur-foundation',
    name: 'MacArthur Foundation',
    url: 'https://www.macfound.org/programs/',
    type: 'foundation',
    region: 'Global',
    categories: ['climate', 'rights', 'media'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'oak-foundation',
    name: 'Oak Foundation',
    url: 'https://oakfnd.org/programmes/',
    type: 'foundation',
    region: 'Global',
    categories: ['environment', 'rights', 'housing'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== FOOD & AGRICULTURE =====
  {
    id: 'ikea-foundation',
    name: 'IKEA Foundation',
    url: 'https://ikeafoundation.org/grants/',
    type: 'corporate',
    region: 'Global',
    categories: ['climate', 'livelihoods', 'refugees'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'rockefeller-food',
    name: 'Rockefeller Foundation - Food',
    url: 'https://www.rockefellerfoundation.org/initiative/food/',
    type: 'foundation',
    region: 'Global',
    categories: ['food', 'agriculture', 'health'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'ceres-trust',
    name: 'Ceres Trust',
    url: 'https://cerestrust.org/grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['agriculture', 'organic', 'sustainability'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'agroecology-fund',
    name: 'Agroecology Fund',
    url: 'https://www.agroecologyfund.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['agriculture', 'indigenous', 'food'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'clif-bar-foundation',
    name: 'Clif Bar Family Foundation',
    url: 'https://clifbarfamilyfoundation.org/Grants-Programs',
    type: 'corporate',
    region: 'Global',
    categories: ['food', 'sustainability', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'whole-planet',
    name: 'Whole Planet Foundation',
    url: 'https://www.wholeplanetfoundation.org/',
    type: 'corporate',
    region: 'Global',
    categories: ['poverty', 'microfinance', 'food'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== IMPACT & SOCIAL ENTERPRISE =====
  {
    id: 'acumen',
    name: 'Acumen Fund',
    url: 'https://acumen.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['impact', 'social enterprise', 'poverty'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'village-capital',
    name: 'Village Capital',
    url: 'https://vilcap.com/accelerators',
    type: 'accelerator',
    region: 'Global',
    categories: ['social enterprise', 'startup', 'impact'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'unreasonable',
    name: 'Unreasonable Group',
    url: 'https://unreasonablegroup.com/ventures/',
    type: 'accelerator',
    region: 'Global',
    categories: ['social enterprise', 'climate', 'impact'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'spring-impact',
    name: 'Spring Impact',
    url: 'https://www.springimpact.org/',
    type: 'accelerator',
    region: 'Global',
    categories: ['social enterprise', 'scaling', 'impact'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'schwab-foundation',
    name: 'Schwab Foundation for Social Entrepreneurship',
    url: 'https://www.schwabfound.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['social enterprise', 'leadership'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'rippleworks',
    name: 'Rippleworks',
    url: 'https://www.rippleworks.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['social enterprise', 'scaling', 'leadership'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== LATIN AMERICA / PERU SPECIFIC =====
  {
    id: 'idb-lab',
    name: 'IDB Lab (Inter-American Development Bank)',
    url: 'https://bidlab.org/en/projects',
    type: 'development',
    region: 'Latin America',
    categories: ['innovation', 'development', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'caf-development',
    name: 'CAF Development Bank of Latin America',
    url: 'https://www.caf.com/en/currently/calls/',
    type: 'development',
    region: 'Latin America',
    categories: ['development', 'sustainability', 'infrastructure'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'usaid-peru',
    name: 'USAID Peru',
    url: 'https://www.usaid.gov/peru/work-with-us/funding-opportunities',
    type: 'government',
    region: 'Peru',
    categories: ['development', 'environment', 'governance'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'fondoempleo-peru',
    name: 'FONDOEMPLEO Peru',
    url: 'https://www.fondoempleo.com.pe/convocatorias/',
    type: 'government',
    region: 'Peru',
    categories: ['employment', 'training', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'andes-amazon-fund',
    name: 'Andes Amazon Fund',
    url: 'https://www.andesamazonfund.org/',
    type: 'foundation',
    region: 'Latin America',
    categories: ['environment', 'indigenous', 'conservation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'rainforest-foundation',
    name: 'Rainforest Foundation',
    url: 'https://www.rainforestfoundation.org/grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'environment', 'rights'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'amazon-watch',
    name: 'Amazon Watch',
    url: 'https://amazonwatch.org/',
    type: 'foundation',
    region: 'Latin America',
    categories: ['indigenous', 'environment', 'rights'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== GRANT AGGREGATORS =====
  {
    id: 'grantwatch',
    name: 'GrantWatch',
    url: 'https://www.grantwatch.com/grant-search.php',
    type: 'aggregator',
    region: 'Global',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'instrumentl',
    name: 'Instrumentl',
    url: 'https://www.instrumentl.com/grants',
    type: 'aggregator',
    region: 'Global',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: false, // Requires subscription
  },
  {
    id: 'grants-gov-us',
    name: 'Grants.gov (US Federal)',
    url: 'https://www.grants.gov/search-grants',
    type: 'government',
    region: 'USA',
    categories: ['all'],
    scrapeMethod: 'api',
    enabled: true,
  },
  {
    id: 'eu-funding-tenders',
    name: 'EU Funding & Tenders Portal',
    url: 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search',
    type: 'government',
    region: 'Europe',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== INDIGENOUS RIGHTS SPECIFIC =====
  {
    id: 'nia-tero',
    name: 'Nia Tero',
    url: 'https://www.niatero.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'land rights', 'sovereignty'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'ifip',
    name: 'International Funders for Indigenous Peoples',
    url: 'https://internationalfunders.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'rights', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'tribal-link',
    name: 'Tribal Link Foundation',
    url: 'https://www.triballink.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'youth', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'amazon-sacred-headwaters',
    name: 'Sacred Headwaters Initiative',
    url: 'https://sacredheadwaters.org/',
    type: 'foundation',
    region: 'Latin America',
    categories: ['indigenous', 'amazon', 'conservation'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== WELLBEING & HEALTH =====
  {
    id: 'wellcome-trust',
    name: 'Wellcome Trust',
    url: 'https://wellcome.org/grant-funding',
    type: 'foundation',
    region: 'Global',
    categories: ['health', 'research', 'mental health'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'robert-wood-johnson',
    name: 'Robert Wood Johnson Foundation',
    url: 'https://www.rwjf.org/en/grants.html',
    type: 'foundation',
    region: 'USA',
    categories: ['health', 'wellbeing', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== AUSTRALIA - FESTIVALS & EVENTS =====
  {
    id: 'festivals-australia',
    name: 'Festivals Australia',
    url: 'https://www.arts.gov.au/funding-and-support/festivals-australia',
    type: 'government',
    region: 'Australia',
    categories: ['festival', 'community', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'city-sydney-festivals',
    name: 'City of Sydney Festivals Sponsorship',
    url: 'https://www.cityofsydney.nsw.gov.au/cultural-support-funding/festivals-and-events-sponsorship',
    type: 'government',
    region: 'Australia',
    categories: ['festival', 'cultural', 'events'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'qld-communities-innovation',
    name: 'Queensland Communities Innovation Fund',
    url: 'https://www.families.qld.gov.au/our-work/families/communities-2032/communities-innovation-fund-responses-to-social-isolation-and-loneliness',
    type: 'government',
    region: 'Australia',
    categories: ['community', 'loneliness', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'australia-post-community',
    name: 'Australia Post Community Grants',
    url: 'https://auspost.com.au/about-us/supporting-communities/grants/community-grants-program',
    type: 'corporate',
    region: 'Australia',
    categories: ['community', 'social', 'connection'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== MINDFULNESS & WELLBEING =====
  {
    id: 'mind-life-institute',
    name: 'Mind & Life Institute',
    url: 'https://www.mindandlife.org/grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['mindfulness', 'research', 'wellbeing'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'trust-meditation',
    name: 'Trust for Meditation Process',
    url: 'https://trustformeditation.org/',
    type: 'foundation',
    region: 'USA',
    categories: ['meditation', 'mindfulness', 'wellbeing'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== FUNCTIONAL BEVERAGES & FOOD INNOVATION =====
  {
    id: 'investbev-accelerator',
    name: 'InvestBev Accelerator',
    url: 'https://www.investbev.com/accelerator',
    type: 'accelerator',
    region: 'USA',
    categories: ['beverage', 'startup', 'investment'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'eit-food',
    name: 'EIT Food',
    url: 'https://www.eitfood.eu/open-calls',
    type: 'accelerator',
    region: 'Europe',
    categories: ['food', 'innovation', 'startup'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== EQUATOR INITIATIVE & UN =====
  {
    id: 'equator-initiative',
    name: 'UNDP Equator Initiative',
    url: 'https://www.equatorinitiative.org/equator-prize/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'sustainability', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'undp-indigenous',
    name: 'UNDP Indigenous Peoples',
    url: 'https://www.undp.org/indigenous-peoples',
    type: 'government',
    region: 'Global',
    categories: ['indigenous', 'development', 'rights'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== DUTCH - ADDITIONAL SOURCES =====
  {
    id: 'fondsen-in-nederland',
    name: 'Fondsen in Nederland (Database)',
    url: 'https://fondseninnederland.nl/fondsen',
    type: 'aggregator',
    region: 'Netherlands',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'social-enterprise-nl',
    name: 'Social Enterprise NL',
    url: 'https://social-enterprise.nl/en/artikelen/financieringsoverzicht/',
    type: 'aggregator',
    region: 'Netherlands',
    categories: ['social enterprise', 'funding'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'mama-cash',
    name: 'Mama Cash',
    url: 'https://www.mamacash.org/en/apply-for-a-grant',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['women', 'rights', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'hivos',
    name: 'Hivos',
    url: 'https://hivos.org/what-we-do/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['rights', 'sustainability', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'solidaridad',
    name: 'Solidaridad',
    url: 'https://www.solidaridadnetwork.org/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['fair trade', 'agriculture', 'cacao'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== CACAO & CHOCOLATE SPECIFIC =====
  {
    id: 'cocoa-horizons',
    name: 'Cocoa Horizons Foundation',
    url: 'https://www.cocoahorizons.org/',
    type: 'corporate',
    region: 'Global',
    categories: ['cacao', 'sustainability', 'farmers'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'fairtrade-cacao',
    name: 'Fairtrade - Cocoa',
    url: 'https://www.fairtrade.net/en/products/Fairtrade_products/cocoa.html',
    type: 'foundation',
    region: 'Global',
    categories: ['fair trade', 'cacao', 'farmers'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'world-cocoa-foundation',
    name: 'World Cocoa Foundation',
    url: 'https://www.worldcocoafoundation.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['cacao', 'sustainability', 'farmers'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== SOCIAL CONNECTION & LONELINESS =====
  {
    id: 'foundation-social-connection',
    name: 'Foundation for Social Connection',
    url: 'https://www.social-connection.org/',
    type: 'foundation',
    region: 'USA',
    categories: ['loneliness', 'community', 'connection'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'ending-loneliness-au',
    name: 'Ending Loneliness Together (AU)',
    url: 'https://endingloneliness.com.au/',
    type: 'foundation',
    region: 'Australia',
    categories: ['loneliness', 'community', 'mental health'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== ADDITIONAL AUSTRALIAN SOURCES =====
  {
    id: 'ian-potter-foundation',
    name: 'Ian Potter Foundation',
    url: 'https://www.ianpotter.org.au/grants/',
    type: 'foundation',
    region: 'Australia',
    categories: ['arts', 'environment', 'health', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'sidney-myer-fund',
    name: 'Sidney Myer Fund',
    url: 'https://myerfoundation.org.au/',
    type: 'foundation',
    region: 'Australia',
    categories: ['arts', 'community', 'indigenous'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'perpetual-impact',
    name: 'Perpetual IMPACT Philanthropy',
    url: 'https://www.perpetual.com.au/philanthropy/impact/',
    type: 'foundation',
    region: 'Australia',
    categories: ['social', 'environment', 'health'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'helen-macpherson-smith',
    name: 'Helen Macpherson Smith Trust',
    url: 'https://hmstrust.org.au/grants/',
    type: 'foundation',
    region: 'Australia',
    categories: ['victoria', 'community', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'food-agility-crc',
    name: 'Food Agility CRC',
    url: 'https://www.foodagility.com/research',
    type: 'government',
    region: 'Australia',
    categories: ['food', 'innovation', 'research'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'fial-grants',
    name: 'Food Innovation Australia Limited',
    url: 'https://fial.com.au/funding/',
    type: 'government',
    region: 'Australia',
    categories: ['food', 'innovation', 'export'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== CHOCOLATE/COCOA SPECIFIC =====
  {
    id: 'tonys-open-chain',
    name: "Tony's Open Chain",
    url: 'https://tonysopenchain.com/',
    type: 'corporate',
    region: 'Global',
    categories: ['cacao', 'ethical', 'supply-chain'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'icco',
    name: 'International Cocoa Organization',
    url: 'https://www.icco.org/',
    type: 'government',
    region: 'Global',
    categories: ['cacao', 'sustainability', 'policy'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'idh-cocoa',
    name: 'IDH Sustainable Trade - Cocoa',
    url: 'https://www.idhsustainabletrade.com/initiative/cocoa/',
    type: 'foundation',
    region: 'Global',
    categories: ['cacao', 'sustainability', 'farmers'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== DOCUMENTARY & FILM =====
  {
    id: 'sundance-documentary',
    name: 'Sundance Documentary Fund',
    url: 'https://www.sundance.org/programs/documentary-fund',
    type: 'foundation',
    region: 'Global',
    categories: ['documentary', 'film', 'storytelling'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'britdoc-foundation',
    name: 'Doc Society (formerly Britdoc)',
    url: 'https://docsociety.org/funding/',
    type: 'foundation',
    region: 'Global',
    categories: ['documentary', 'impact', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'idfa-bertha-fund',
    name: 'IDFA Bertha Fund',
    url: 'https://www.idfa.nl/en/info/idfa-bertha-fund',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['documentary', 'film'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'catapult-film-fund',
    name: 'Catapult Film Fund',
    url: 'https://catapultfilmfund.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['documentary', 'film', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== SWISS SOURCES =====
  {
    id: 'swiss-foundation-culture',
    name: 'Swiss Arts Council Pro Helvetia',
    url: 'https://prohelvetia.ch/en/funding/',
    type: 'government',
    region: 'Switzerland',
    categories: ['culture', 'arts', 'exchange'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'migros-culture',
    name: 'Migros Culture Percentage',
    url: 'https://www.migros-kulturprozent.ch/en/',
    type: 'corporate',
    region: 'Switzerland',
    categories: ['culture', 'social', 'sustainability'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== MENTAL HEALTH & WELLBEING =====
  {
    id: 'movember-foundation',
    name: 'Movember Foundation',
    url: 'https://movember.com/about/funding/',
    type: 'foundation',
    region: 'Global',
    categories: ['mental health', 'wellbeing', 'men'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'beyond-blue',
    name: 'Beyond Blue',
    url: 'https://www.beyondblue.org.au/about-us/research-projects',
    type: 'foundation',
    region: 'Australia',
    categories: ['mental health', 'wellbeing', 'research'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== UK SOURCES =====
  {
    id: 'paul-hamlyn-foundation',
    name: 'Paul Hamlyn Foundation',
    url: 'https://www.phf.org.uk/funds/',
    type: 'foundation',
    region: 'UK',
    categories: ['arts', 'education', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'esmee-fairbairn',
    name: 'Esmée Fairbairn Foundation',
    url: 'https://esmeefairbairn.org.uk/our-grants/',
    type: 'foundation',
    region: 'UK',
    categories: ['environment', 'arts', 'food'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'british-council',
    name: 'British Council Grants',
    url: 'https://www.britishcouncil.org/arts/funding-opportunities',
    type: 'government',
    region: 'UK',
    categories: ['culture', 'exchange', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== FOOD SYSTEMS =====
  {
    id: 'ellen-macarthur-food',
    name: 'Ellen MacArthur Foundation - Food',
    url: 'https://www.ellenmacarthurfoundation.org/topics/food/',
    type: 'foundation',
    region: 'Global',
    categories: ['food', 'circular', 'sustainability'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'global-food-change',
    name: 'Global Alliance for the Future of Food',
    url: 'https://futureoffood.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['food', 'sustainability', 'systems'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== ADDITIONAL LATAM =====
  {
    id: 'codespa-foundation',
    name: 'CODESPA Foundation',
    url: 'https://www.codespa.org/en/',
    type: 'foundation',
    region: 'Latin America',
    categories: ['development', 'social enterprise', 'agriculture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'avina-foundation',
    name: 'Avina Foundation',
    url: 'https://www.avina.net/en/',
    type: 'foundation',
    region: 'Latin America',
    categories: ['sustainability', 'social', 'democracy'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'banco-interamericano',
    name: 'BID Lab (IDB Lab)',
    url: 'https://bidlab.org/en',
    type: 'development',
    region: 'Latin America',
    categories: ['innovation', 'technology', 'inclusion'],
    scrapeMethod: 'html',
    enabled: true,
  },
]

// Categories that Sacred Foundation focuses on
export const relevantCategories = [
  'indigenous',
  'culture',
  'heritage',
  'food',
  'agriculture',
  'sustainability',
  'environment',
  'social enterprise',
  'community',
  'wellbeing',
  'research',
]
