// Grant Discovery Configuration for Sacred Foundation
// Keywords and sources for finding relevant grants

export const sacredKeywords = {
  // Primary focus areas - from Sacred Bible + Sep 2026 Stichting strategy
  primary: [
    'cacao',
    'ceremonial cacao',
    'criollo',
    'heirloom cacao',
    'indigenous',
    'indigenous communities',
    'indigenous peoples',
    'indigenous-led',
    'ceremony',
    'traditional knowledge',
    'ancestral wisdom',
    'sacred plants',
    'plant medicine',
    'native communities',
    'first nations',
    'aboriginal',
    'tribal communities',
    'ashaninka',
    'maya',
    'aztec',
    // Talent development & music (new domain)
    'talent development',
    'emerging artist fund',
    'music production grant',
    'artist development',
    'recording grant',
    'debut album funding',
    // Dutch primary terms
    'talentontwikkeling',
    'opkomend talent',
    'productiesubsidie',
    'muziekproductie',
    'makersregeling',
    'jong talent',
    'inheemse volken',
    'cultureel erfgoed',
    'podiumkunsten',
    'muziekfonds',
    'componeren',
    'artiest subsidie',
    'cultuursubsidie',
    'kunstenaar subsidie',
    'debuut',
    'werkbijdrage',
    'projectsubsidie',
    'meerjarige subsidie',
    'basisinfrastructuur',
    'festivalsubsidie',
    'concertsubsidie',
    'opnamefonds',
    'muziektheater',
    'popsubsidie',
    'jazzsubsidie',
    'wereldmuziek',
    'muziekonderwijs',
  ],

  // Secondary relevance - from Sacred's Theory of Change
  secondary: [
    // Sustainability & Environment
    'sustainability',
    'regenerative agriculture',
    'regenerative farming',
    'agroforestry',
    'permaculture',
    'deforestation',
    'rainforest preservation',
    'amazon protection',
    'forest conservation',
    'climate action',
    'biodiversity',

    // Food & Trade
    'food systems',
    'food sovereignty',
    'fair trade',
    'direct trade',
    'ethical sourcing',
    'supply chain transparency',
    'smallholder farmers',
    'small-scale farmers',
    'artisanal',
    'premium food',
    'chocolate',
    'cocoa',

    // Mental Health & Wellbeing (loneliness epidemic)
    'wellbeing',
    'mental health',
    'mental wellness',
    'loneliness',
    'social connection',
    'community building',
    'social isolation',
    'holistic health',
    'mindfulness',

    // Alcohol alternatives (sober curious movement)
    'alcohol alternative',
    'non-alcoholic',
    'sober curious',
    'mindful drinking',
    'functional beverage',
    'alcohol-free youth events',
    'healthy alternatives',

    // Cultural & Heritage
    'cultural preservation',
    'cultural heritage',
    'intangible heritage',
    'traditional practices',
    'ancestral knowledge',
    'cultural exchange',

    // Social Enterprise
    'social enterprise',
    'social entrepreneurship',
    'impact investing',
    'community development',
    'cooperative',
    'B Corp',

    // Land Rights
    'land rights',
    'indigenous sovereignty',
    'territorial rights',

    // Film & Documentary
    'documentary funding',
    'film production grant',
    'cross-media',
    'immersive performance',
    'interdisciplinary arts',

    // Education & Supply Chains
    'development education',
    'global citizenship',
    'awareness raising',
    'fair trade education',
    'sustainable supply chains',
    'development cooperation',

    // Dutch secondary terms
    'alcoholvrij',
    'eenzaamheid',
    'sociale verbinding',
    'jongerenwelzijn',
    'preventie',
    'mentale gezondheid',
    'ontmoeting',
    'mondiaal burgerschap',
    'bewustwording',
    'ontwikkelingssamenwerking',
    'eerlijke handel',
    'ketentransparantie',
    'educatieprogramma',
    'documentaire fonds',
    'filmproductie',
    'mediakunst',
    'crossmediaal',
    'interdisciplinair',
    'nieuwe makers',
    'culturele uitwisseling',
    'landrechten',
    'traditionele kennis',
    'regenwoud',
    'ontbossing',
    'biodiversiteit',
    'natuurbescherming',
    'klimaat',
    'duurzaamheid',
    'cultuurparticipatie',
    'erfgoedsubsidie',
    'spreiding',
    'internationalisering',
    'kunsteducatie',
    'maatschappelijk betrokken',
    'immaterieel erfgoed',
    'creatieve industrie',
    'social impact',
    'makersfonds',
    'stimuleringsfonds',
    'vermogensfonds',
    'cultuurfonds op naam',
    'provinciale subsidie',
    'gemeentelijke subsidie',
  ],

  // Geographic focus
  geographic: [
    'Peru',
    'Peruvian',
    'Latin America',
    'South America',
    'Central America',
    'Andes',
    'Andean',
    'Amazon',
    'Amazonian',
    'Australia',
    'Australian',
    'Netherlands',
    'Dutch',
    'Holland',
    'Europe',
    'European',
    'Global South',
    'Ecuador',
    'Colombia',
    'Bolivia',
    'Guatemala',
    'Mexico',
    'Indonesia',
    'West Africa',
    'Ghana',
    'Ivory Coast',
  ],

  // Negative keywords (exclude grants mentioning these)
  exclude: [
    'fossil fuel',
    'oil and gas',
    'mining extraction',
    'tobacco',
    'gambling',
    'weapons',
    'military',
  ]
}

// Scoring weights
export const relevanceWeights = {
  primaryKeyword: 30,      // Points per primary keyword match
  secondaryKeyword: 15,    // Points per secondary keyword match
  geographicMatch: 20,     // Points per geographic match
  excludeKeyword: -100,    // Penalty for excluded keywords
  amountBonus: {           // Bonus based on grant amount
    small: 5,              // < €10k
    medium: 10,            // €10k - €50k
    large: 15,             // €50k - €200k
    major: 20,             // > €200k
  },
  deadlineBonus: {
    urgent: 10,            // < 30 days
    soon: 5,               // 30-90 days
  }
}

// Minimum score to show a discovered grant (lowered to catch more potential grants)
export const minimumRelevanceScore = 5

// Grant databases and sources to scrape
export const grantSources = [
  // Australian Sources
  {
    id: 'grants-gov-au',
    name: 'Grants.gov.au',
    url: 'https://www.grants.gov.au/',
    searchUrl: 'https://www.grants.gov.au/Search/SearchGrant',
    type: 'government',
    region: 'Australia',
    categories: ['all'],
    scrapeMethod: 'api', // Has API
    enabled: true,
  },
  {
    id: 'business-gov-au',
    name: 'Business.gov.au Grants Finder',
    url: 'https://business.gov.au/grants-and-programs',
    type: 'government',
    region: 'Australia',
    categories: ['business', 'innovation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'philanthropy-aus',
    name: 'Philanthropy Australia',
    url: 'https://www.philanthropy.org.au/tools-resources/funding-opportunities/',
    type: 'foundation',
    region: 'Australia',
    categories: ['social', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // Dutch/European Sources
  {
    id: 'cultuurfonds',
    name: 'Prins Bernhard Cultuurfonds',
    url: 'https://www.cultuurfonds.nl/aanvragen',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['culture', 'heritage'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'doen-foundation',
    name: 'DOEN Foundation',
    url: 'https://www.doen.nl/en/what-we-do',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['sustainability', 'culture', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'oranje-fonds',
    name: 'Oranje Fonds',
    url: 'https://www.oranjefonds.nl/aanvragen',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['social', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'nwo',
    name: 'NWO - Dutch Research Council',
    url: 'https://www.nwo.nl/en/calls',
    type: 'government',
    region: 'Netherlands',
    categories: ['research', 'innovation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'creative-europe',
    name: 'Creative Europe',
    url: 'https://culture.ec.europa.eu/funding',
    type: 'government',
    region: 'Europe',
    categories: ['culture', 'creative'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'horizon-europe',
    name: 'Horizon Europe',
    url: 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/',
    type: 'government',
    region: 'Europe',
    categories: ['research', 'innovation', 'sustainability'],
    scrapeMethod: 'api',
    enabled: true,
  },

  // International/Global Sources
  {
    id: 'global-giving',
    name: 'GlobalGiving',
    url: 'https://www.globalgiving.org/grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['social', 'community', 'environment'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'ashoka',
    name: 'Ashoka Fellowships',
    url: 'https://www.ashoka.org/en/our-network/ashoka-fellows',
    type: 'foundation',
    region: 'Global',
    categories: ['social enterprise', 'innovation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'skoll',
    name: 'Skoll Foundation',
    url: 'https://skoll.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['social enterprise', 'impact'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'echoing-green',
    name: 'Echoing Green',
    url: 'https://echoinggreen.org/fellowship/',
    type: 'foundation',
    region: 'Global',
    categories: ['social enterprise', 'leadership'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'patagonia-env',
    name: 'Patagonia Environmental Grants',
    url: 'https://www.patagonia.com/how-we-fund/',
    type: 'corporate',
    region: 'Global',
    categories: ['environment', 'sustainability'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'ben-jerry',
    name: 'Ben & Jerry\'s Foundation',
    url: 'https://benandjerrysfoundation.org/the-grassroots-organizing-for-social-change-program/',
    type: 'corporate',
    region: 'Global',
    categories: ['social', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // Food & Agriculture Specific
  {
    id: 'slow-food',
    name: 'Slow Food Foundation',
    url: 'https://www.fondazioneslowfood.com/en/what-we-do/',
    type: 'foundation',
    region: 'Global',
    categories: ['food', 'sustainability', 'indigenous'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'agrifood-atlas',
    name: 'Agrifood Atlas',
    url: 'https://www.boell.de/en/agrifood-atlas',
    type: 'foundation',
    region: 'Global',
    categories: ['food', 'agriculture'],
    scrapeMethod: 'html',
    enabled: false, // Info resource, not grants
  },
  {
    id: 'christensen-fund',
    name: 'The Christensen Fund',
    url: 'https://www.christensenfund.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'biodiversity', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'swift-foundation',
    name: 'Swift Foundation',
    url: 'https://swiftfoundation.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'environment', 'rights'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // Indigenous & Cultural Preservation
  {
    id: 'first-peoples',
    name: 'First Peoples Worldwide',
    url: 'https://www.firstpeoplesworldwide.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'rights'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'cultural-survival',
    name: 'Cultural Survival',
    url: 'https://www.culturalsurvival.org/grants',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'culture', 'media'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // Aggregator Sites
  {
    id: 'funds-for-ngos',
    name: 'Funds for NGOs',
    url: 'https://www2.fundsforngos.org/',
    type: 'aggregator',
    region: 'Global',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'candid',
    name: 'Candid (Foundation Directory)',
    url: 'https://candid.org/find-funding',
    type: 'aggregator',
    region: 'Global',
    categories: ['all'],
    scrapeMethod: 'api',
    enabled: false, // Requires subscription
  },

  // ===== ADDITIONAL DUTCH FOUNDATIONS =====
  {
    id: 'vsbfonds',
    name: 'VSBfonds',
    url: 'https://www.vsbfonds.nl/aanvragen',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['culture', 'social', 'education'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'adessium',
    name: 'Adessium Foundation',
    url: 'https://www.adessium.org/what-we-support/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['sustainability', 'social', 'journalism'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'triodos-foundation',
    name: 'Triodos Foundation',
    url: 'https://www.triodos.nl/triodos-foundation',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['sustainability', 'culture', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'iona-stichting',
    name: 'Iona Stichting',
    url: 'https://www.ionastichting.nl/aanvragen/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['culture', 'spirituality', 'education'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'haella-stichting',
    name: 'Haëlla Stichting',
    url: 'https://www.haella.nl/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['development', 'social', 'sustainability'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'stichting-democratie-media',
    name: 'Stichting Democratie en Media',
    url: 'https://www.democratieenmedia.nl/subsidies/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['media', 'democracy', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'mondriaan-fonds',
    name: 'Mondriaan Fonds',
    url: 'https://www.mondriaanfonds.nl/aanvragen/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'art', 'heritage'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'fonds21',
    name: 'Fonds 21',
    url: 'https://www.fonds21.nl/aanvragen',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['culture', 'youth', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== MAJOR GLOBAL FOUNDATIONS =====
  {
    id: 'ford-foundation',
    name: 'Ford Foundation',
    url: 'https://www.fordfoundation.org/work/our-grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'rights', 'equality', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'open-society',
    name: 'Open Society Foundations',
    url: 'https://www.opensocietyfoundations.org/grants',
    type: 'foundation',
    region: 'Global',
    categories: ['rights', 'justice', 'democracy', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'packard-foundation',
    name: 'David and Lucile Packard Foundation',
    url: 'https://www.packard.org/grants-and-investments/',
    type: 'foundation',
    region: 'Global',
    categories: ['environment', 'sustainability', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: '11th-hour-project',
    name: '11th Hour Project',
    url: 'https://11thhourproject.org/grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['environment', 'food', 'sustainability'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'hewlett-foundation',
    name: 'William and Flora Hewlett Foundation',
    url: 'https://hewlett.org/grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['environment', 'education', 'democracy'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'macarthur-foundation',
    name: 'MacArthur Foundation',
    url: 'https://www.macfound.org/programs/',
    type: 'foundation',
    region: 'Global',
    categories: ['climate', 'rights', 'media'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'oak-foundation',
    name: 'Oak Foundation',
    url: 'https://oakfnd.org/programmes/',
    type: 'foundation',
    region: 'Global',
    categories: ['environment', 'rights', 'housing'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== FOOD & AGRICULTURE =====
  {
    id: 'ikea-foundation',
    name: 'IKEA Foundation',
    url: 'https://ikeafoundation.org/grants/',
    type: 'corporate',
    region: 'Global',
    categories: ['climate', 'livelihoods', 'refugees'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'rockefeller-food',
    name: 'Rockefeller Foundation - Food',
    url: 'https://www.rockefellerfoundation.org/initiative/food/',
    type: 'foundation',
    region: 'Global',
    categories: ['food', 'agriculture', 'health'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'ceres-trust',
    name: 'Ceres Trust',
    url: 'https://cerestrust.org/grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['agriculture', 'organic', 'sustainability'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'agroecology-fund',
    name: 'Agroecology Fund',
    url: 'https://www.agroecologyfund.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['agriculture', 'indigenous', 'food'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'clif-bar-foundation',
    name: 'Clif Bar Family Foundation',
    url: 'https://clifbarfamilyfoundation.org/Grants-Programs',
    type: 'corporate',
    region: 'Global',
    categories: ['food', 'sustainability', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'whole-planet',
    name: 'Whole Planet Foundation',
    url: 'https://www.wholeplanetfoundation.org/',
    type: 'corporate',
    region: 'Global',
    categories: ['poverty', 'microfinance', 'food'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== IMPACT & SOCIAL ENTERPRISE =====
  {
    id: 'acumen',
    name: 'Acumen Fund',
    url: 'https://acumen.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['impact', 'social enterprise', 'poverty'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'village-capital',
    name: 'Village Capital',
    url: 'https://vilcap.com/accelerators',
    type: 'accelerator',
    region: 'Global',
    categories: ['social enterprise', 'startup', 'impact'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'unreasonable',
    name: 'Unreasonable Group',
    url: 'https://unreasonablegroup.com/ventures/',
    type: 'accelerator',
    region: 'Global',
    categories: ['social enterprise', 'climate', 'impact'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'spring-impact',
    name: 'Spring Impact',
    url: 'https://www.springimpact.org/',
    type: 'accelerator',
    region: 'Global',
    categories: ['social enterprise', 'scaling', 'impact'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'schwab-foundation',
    name: 'Schwab Foundation for Social Entrepreneurship',
    url: 'https://www.schwabfound.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['social enterprise', 'leadership'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'rippleworks',
    name: 'Rippleworks',
    url: 'https://www.rippleworks.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['social enterprise', 'scaling', 'leadership'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== LATIN AMERICA / PERU SPECIFIC =====
  {
    id: 'idb-lab',
    name: 'IDB Lab (Inter-American Development Bank)',
    url: 'https://bidlab.org/en/projects',
    type: 'development',
    region: 'Latin America',
    categories: ['innovation', 'development', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'caf-development',
    name: 'CAF Development Bank of Latin America',
    url: 'https://www.caf.com/en/currently/calls/',
    type: 'development',
    region: 'Latin America',
    categories: ['development', 'sustainability', 'infrastructure'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'usaid-peru',
    name: 'USAID Peru',
    url: 'https://www.usaid.gov/peru/work-with-us/funding-opportunities',
    type: 'government',
    region: 'Peru',
    categories: ['development', 'environment', 'governance'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'fondoempleo-peru',
    name: 'FONDOEMPLEO Peru',
    url: 'https://www.fondoempleo.com.pe/convocatorias/',
    type: 'government',
    region: 'Peru',
    categories: ['employment', 'training', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'andes-amazon-fund',
    name: 'Andes Amazon Fund',
    url: 'https://www.andesamazonfund.org/',
    type: 'foundation',
    region: 'Latin America',
    categories: ['environment', 'indigenous', 'conservation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'rainforest-foundation',
    name: 'Rainforest Foundation',
    url: 'https://www.rainforestfoundation.org/grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'environment', 'rights'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'amazon-watch',
    name: 'Amazon Watch',
    url: 'https://amazonwatch.org/',
    type: 'foundation',
    region: 'Latin America',
    categories: ['indigenous', 'environment', 'rights'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== GRANT AGGREGATORS =====
  {
    id: 'grantwatch',
    name: 'GrantWatch',
    url: 'https://www.grantwatch.com/grant-search.php',
    type: 'aggregator',
    region: 'Global',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'instrumentl',
    name: 'Instrumentl',
    url: 'https://www.instrumentl.com/grants',
    type: 'aggregator',
    region: 'Global',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: false, // Requires subscription
  },
  {
    id: 'grants-gov-us',
    name: 'Grants.gov (US Federal)',
    url: 'https://www.grants.gov/search-grants',
    type: 'government',
    region: 'USA',
    categories: ['all'],
    scrapeMethod: 'api',
    enabled: true,
  },
  {
    id: 'eu-funding-tenders',
    name: 'EU Funding & Tenders Portal',
    url: 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search',
    type: 'government',
    region: 'Europe',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== INDIGENOUS RIGHTS SPECIFIC =====
  {
    id: 'nia-tero',
    name: 'Nia Tero',
    url: 'https://www.niatero.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'land rights', 'sovereignty'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'ifip',
    name: 'International Funders for Indigenous Peoples',
    url: 'https://internationalfunders.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'rights', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'tribal-link',
    name: 'Tribal Link Foundation',
    url: 'https://www.triballink.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'youth', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'amazon-sacred-headwaters',
    name: 'Sacred Headwaters Initiative',
    url: 'https://sacredheadwaters.org/',
    type: 'foundation',
    region: 'Latin America',
    categories: ['indigenous', 'amazon', 'conservation'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== WELLBEING & HEALTH =====
  {
    id: 'wellcome-trust',
    name: 'Wellcome Trust',
    url: 'https://wellcome.org/grant-funding',
    type: 'foundation',
    region: 'Global',
    categories: ['health', 'research', 'mental health'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'robert-wood-johnson',
    name: 'Robert Wood Johnson Foundation',
    url: 'https://www.rwjf.org/en/grants.html',
    type: 'foundation',
    region: 'USA',
    categories: ['health', 'wellbeing', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== AUSTRALIA - FESTIVALS & EVENTS =====
  {
    id: 'festivals-australia',
    name: 'Festivals Australia',
    url: 'https://www.arts.gov.au/funding-and-support/festivals-australia',
    type: 'government',
    region: 'Australia',
    categories: ['festival', 'community', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'city-sydney-festivals',
    name: 'City of Sydney Festivals Sponsorship',
    url: 'https://www.cityofsydney.nsw.gov.au/cultural-support-funding/festivals-and-events-sponsorship',
    type: 'government',
    region: 'Australia',
    categories: ['festival', 'cultural', 'events'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'qld-communities-innovation',
    name: 'Queensland Communities Innovation Fund',
    url: 'https://www.families.qld.gov.au/our-work/families/communities-2032/communities-innovation-fund-responses-to-social-isolation-and-loneliness',
    type: 'government',
    region: 'Australia',
    categories: ['community', 'loneliness', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'australia-post-community',
    name: 'Australia Post Community Grants',
    url: 'https://auspost.com.au/about-us/supporting-communities/grants/community-grants-program',
    type: 'corporate',
    region: 'Australia',
    categories: ['community', 'social', 'connection'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== MINDFULNESS & WELLBEING =====
  {
    id: 'mind-life-institute',
    name: 'Mind & Life Institute',
    url: 'https://www.mindandlife.org/grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['mindfulness', 'research', 'wellbeing'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'trust-meditation',
    name: 'Trust for Meditation Process',
    url: 'https://trustformeditation.org/',
    type: 'foundation',
    region: 'USA',
    categories: ['meditation', 'mindfulness', 'wellbeing'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== FUNCTIONAL BEVERAGES & FOOD INNOVATION =====
  {
    id: 'investbev-accelerator',
    name: 'InvestBev Accelerator',
    url: 'https://www.investbev.com/accelerator',
    type: 'accelerator',
    region: 'USA',
    categories: ['beverage', 'startup', 'investment'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'eit-food',
    name: 'EIT Food',
    url: 'https://www.eitfood.eu/open-calls',
    type: 'accelerator',
    region: 'Europe',
    categories: ['food', 'innovation', 'startup'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== EQUATOR INITIATIVE & UN =====
  {
    id: 'equator-initiative',
    name: 'UNDP Equator Initiative',
    url: 'https://www.equatorinitiative.org/equator-prize/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'sustainability', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'undp-indigenous',
    name: 'UNDP Indigenous Peoples',
    url: 'https://www.undp.org/indigenous-peoples',
    type: 'government',
    region: 'Global',
    categories: ['indigenous', 'development', 'rights'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== DUTCH - ADDITIONAL SOURCES =====
  {
    id: 'fondsen-in-nederland',
    name: 'Fondsen in Nederland (Database)',
    url: 'https://fondseninnederland.nl/fondsen',
    type: 'aggregator',
    region: 'Netherlands',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'social-enterprise-nl',
    name: 'Social Enterprise NL',
    url: 'https://social-enterprise.nl/en/artikelen/financieringsoverzicht/',
    type: 'aggregator',
    region: 'Netherlands',
    categories: ['social enterprise', 'funding'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'mama-cash',
    name: 'Mama Cash',
    url: 'https://www.mamacash.org/en/apply-for-a-grant',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['women', 'rights', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'hivos',
    name: 'Hivos',
    url: 'https://hivos.org/what-we-do/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['rights', 'sustainability', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'solidaridad',
    name: 'Solidaridad',
    url: 'https://www.solidaridadnetwork.org/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['fair trade', 'agriculture', 'cacao'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== CACAO & CHOCOLATE SPECIFIC =====
  {
    id: 'cocoa-horizons',
    name: 'Cocoa Horizons Foundation',
    url: 'https://www.cocoahorizons.org/',
    type: 'corporate',
    region: 'Global',
    categories: ['cacao', 'sustainability', 'farmers'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'fairtrade-cacao',
    name: 'Fairtrade - Cocoa',
    url: 'https://www.fairtrade.net/en/products/Fairtrade_products/cocoa.html',
    type: 'foundation',
    region: 'Global',
    categories: ['fair trade', 'cacao', 'farmers'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'world-cocoa-foundation',
    name: 'World Cocoa Foundation',
    url: 'https://www.worldcocoafoundation.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['cacao', 'sustainability', 'farmers'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== SOCIAL CONNECTION & LONELINESS =====
  {
    id: 'foundation-social-connection',
    name: 'Foundation for Social Connection',
    url: 'https://www.social-connection.org/',
    type: 'foundation',
    region: 'USA',
    categories: ['loneliness', 'community', 'connection'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'ending-loneliness-au',
    name: 'Ending Loneliness Together (AU)',
    url: 'https://endingloneliness.com.au/',
    type: 'foundation',
    region: 'Australia',
    categories: ['loneliness', 'community', 'mental health'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== ADDITIONAL AUSTRALIAN SOURCES =====
  {
    id: 'ian-potter-foundation',
    name: 'Ian Potter Foundation',
    url: 'https://www.ianpotter.org.au/grants/',
    type: 'foundation',
    region: 'Australia',
    categories: ['arts', 'environment', 'health', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'sidney-myer-fund',
    name: 'Sidney Myer Fund',
    url: 'https://myerfoundation.org.au/',
    type: 'foundation',
    region: 'Australia',
    categories: ['arts', 'community', 'indigenous'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'perpetual-impact',
    name: 'Perpetual IMPACT Philanthropy',
    url: 'https://www.perpetual.com.au/philanthropy/impact/',
    type: 'foundation',
    region: 'Australia',
    categories: ['social', 'environment', 'health'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'helen-macpherson-smith',
    name: 'Helen Macpherson Smith Trust',
    url: 'https://hmstrust.org.au/grants/',
    type: 'foundation',
    region: 'Australia',
    categories: ['victoria', 'community', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'food-agility-crc',
    name: 'Food Agility CRC',
    url: 'https://www.foodagility.com/research',
    type: 'government',
    region: 'Australia',
    categories: ['food', 'innovation', 'research'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'fial-grants',
    name: 'Food Innovation Australia Limited',
    url: 'https://fial.com.au/funding/',
    type: 'government',
    region: 'Australia',
    categories: ['food', 'innovation', 'export'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== CHOCOLATE/COCOA SPECIFIC =====
  {
    id: 'tonys-open-chain',
    name: "Tony's Open Chain",
    url: 'https://tonysopenchain.com/',
    type: 'corporate',
    region: 'Global',
    categories: ['cacao', 'ethical', 'supply-chain'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'icco',
    name: 'International Cocoa Organization',
    url: 'https://www.icco.org/',
    type: 'government',
    region: 'Global',
    categories: ['cacao', 'sustainability', 'policy'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'idh-cocoa',
    name: 'IDH Sustainable Trade - Cocoa',
    url: 'https://www.idhsustainabletrade.com/initiative/cocoa/',
    type: 'foundation',
    region: 'Global',
    categories: ['cacao', 'sustainability', 'farmers'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== DOCUMENTARY & FILM =====
  {
    id: 'sundance-documentary',
    name: 'Sundance Documentary Fund',
    url: 'https://www.sundance.org/programs/documentary-fund',
    type: 'foundation',
    region: 'Global',
    categories: ['documentary', 'film', 'storytelling'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'britdoc-foundation',
    name: 'Doc Society (formerly Britdoc)',
    url: 'https://docsociety.org/funding/',
    type: 'foundation',
    region: 'Global',
    categories: ['documentary', 'impact', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'idfa-bertha-fund',
    name: 'IDFA Bertha Fund',
    url: 'https://www.idfa.nl/en/info/idfa-bertha-fund',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['documentary', 'film'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'catapult-film-fund',
    name: 'Catapult Film Fund',
    url: 'https://catapultfilmfund.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['documentary', 'film', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== SWISS SOURCES =====
  {
    id: 'swiss-foundation-culture',
    name: 'Swiss Arts Council Pro Helvetia',
    url: 'https://prohelvetia.ch/en/funding/',
    type: 'government',
    region: 'Switzerland',
    categories: ['culture', 'arts', 'exchange'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'migros-culture',
    name: 'Migros Culture Percentage',
    url: 'https://www.migros-kulturprozent.ch/en/',
    type: 'corporate',
    region: 'Switzerland',
    categories: ['culture', 'social', 'sustainability'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== MENTAL HEALTH & WELLBEING =====
  {
    id: 'movember-foundation',
    name: 'Movember Foundation',
    url: 'https://movember.com/about/funding/',
    type: 'foundation',
    region: 'Global',
    categories: ['mental health', 'wellbeing', 'men'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'beyond-blue',
    name: 'Beyond Blue',
    url: 'https://www.beyondblue.org.au/about-us/research-projects',
    type: 'foundation',
    region: 'Australia',
    categories: ['mental health', 'wellbeing', 'research'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== UK SOURCES =====
  {
    id: 'paul-hamlyn-foundation',
    name: 'Paul Hamlyn Foundation',
    url: 'https://www.phf.org.uk/funds/',
    type: 'foundation',
    region: 'UK',
    categories: ['arts', 'education', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'esmee-fairbairn',
    name: 'Esmée Fairbairn Foundation',
    url: 'https://esmeefairbairn.org.uk/our-grants/',
    type: 'foundation',
    region: 'UK',
    categories: ['environment', 'arts', 'food'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'british-council',
    name: 'British Council Grants',
    url: 'https://www.britishcouncil.org/arts/funding-opportunities',
    type: 'government',
    region: 'UK',
    categories: ['culture', 'exchange', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== FOOD SYSTEMS =====
  {
    id: 'ellen-macarthur-food',
    name: 'Ellen MacArthur Foundation - Food',
    url: 'https://www.ellenmacarthurfoundation.org/topics/food/',
    type: 'foundation',
    region: 'Global',
    categories: ['food', 'circular', 'sustainability'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'global-food-change',
    name: 'Global Alliance for the Future of Food',
    url: 'https://futureoffood.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['food', 'sustainability', 'systems'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== ADDITIONAL LATAM =====
  {
    id: 'codespa-foundation',
    name: 'CODESPA Foundation',
    url: 'https://www.codespa.org/en/',
    type: 'foundation',
    region: 'Latin America',
    categories: ['development', 'social enterprise', 'agriculture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'avina-foundation',
    name: 'Avina Foundation',
    url: 'https://www.avina.net/en/',
    type: 'foundation',
    region: 'Latin America',
    categories: ['sustainability', 'social', 'democracy'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'banco-interamericano',
    name: 'BID Lab (IDB Lab)',
    url: 'https://bidlab.org/en',
    type: 'development',
    region: 'Latin America',
    categories: ['innovation', 'technology', 'inclusion'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ============================================
  // ===== EXPANDED DUTCH SOURCES (NL-FIRST) =====
  // ============================================

  // ===== DUTCH GOVERNMENT SUBSIDY PORTALS =====
  {
    id: 'subsidieregister-overheid',
    name: 'Subsidieregister Overheid.nl',
    url: 'https://subsidieregister.overheid.nl/',
    type: 'government',
    region: 'Netherlands',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: true,
    priority: 'high',
  },
  {
    id: 'rvo-subsidies',
    name: 'RVO.nl — Rijksdienst voor Ondernemend Nederland',
    url: 'https://www.rvo.nl/subsidies-financiering',
    type: 'government',
    region: 'Netherlands',
    categories: ['business', 'innovation', 'sustainability', 'export'],
    scrapeMethod: 'html',
    enabled: true,
    priority: 'high',
  },
  {
    id: 'vindsubsidies',
    name: 'Vindsubsidies.nl',
    url: 'https://www.vindsubsidies.nl/subsidies',
    type: 'aggregator',
    region: 'Netherlands',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: true,
    priority: 'high',
  },
  {
    id: 'subsidie-nl',
    name: 'Subsidie.nl',
    url: 'https://www.subsidie.nl/subsidies',
    type: 'aggregator',
    region: 'Netherlands',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'overheid-nl-subsidies',
    name: 'Overheid.nl — Subsidies',
    url: 'https://www.overheid.nl/subsidies',
    type: 'government',
    region: 'Netherlands',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== DUTCH MUSIC & PERFORMING ARTS FUNDS =====
  {
    id: 'fonds-podiumkunsten',
    name: 'Fonds Podiumkunsten',
    url: 'https://fondspodiumkunsten.nl/nl/subsidies/',
    type: 'government',
    region: 'Netherlands',
    categories: ['music', 'performing-arts', 'dance', 'theater'],
    scrapeMethod: 'html',
    enabled: true,
    priority: 'high',
  },
  {
    id: 'fonds-podiumkunsten-projecten',
    name: 'Fonds Podiumkunsten — Projectsubsidies',
    url: 'https://fondspodiumkunsten.nl/nl/subsidies/projectsubsidies/',
    type: 'government',
    region: 'Netherlands',
    categories: ['music', 'performing-arts', 'projects'],
    scrapeMethod: 'html',
    enabled: true,
    priority: 'high',
  },
  {
    id: 'fonds-cultuurparticipatie',
    name: 'Fonds voor Cultuurparticipatie',
    url: 'https://www.cultuurparticipatie.nl/subsidies',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'participation', 'education', 'music'],
    scrapeMethod: 'html',
    enabled: true,
    priority: 'high',
  },
  {
    id: 'stimuleringsfonds',
    name: 'Stimuleringsfonds Creatieve Industrie',
    url: 'https://stimuleringsfonds.nl/subsidies/',
    type: 'government',
    region: 'Netherlands',
    categories: ['creative', 'design', 'digital', 'architecture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'filmfonds-nl',
    name: 'Nederlands Filmfonds',
    url: 'https://www.filmfonds.nl/page/subsidies',
    type: 'government',
    region: 'Netherlands',
    categories: ['film', 'documentary', 'animation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'letterenfonds',
    name: 'Nederlands Letterenfonds',
    url: 'https://www.letterenfonds.nl/subsidies',
    type: 'government',
    region: 'Netherlands',
    categories: ['literature', 'translation', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'buma-cultuur',
    name: 'Buma Music in Motion (Buma Cultuur)',
    url: 'https://www.bumacultuur.nl/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['music', 'festival', 'conference'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'sena-performers',
    name: 'Sena Performers — Muziekproductie',
    url: 'https://www.sfrfrg.nl/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['music', 'recording', 'production'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'norma-fonds',
    name: 'Stichting NORMA Fonds',
    url: 'https://www.normafonds.nl/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['music', 'performing-arts', 'musicians'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'popunie',
    name: 'Popunie Rotterdam',
    url: 'https://www.popunie.nl/subsidies/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['music', 'pop', 'talent'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== CULTUURFONDS OP NAAM (Named Sub-funds) =====
  {
    id: 'cultuurfonds-op-naam',
    name: 'Prins Bernhard Cultuurfonds — Fondsen op Naam',
    url: 'https://www.cultuurfonds.nl/fondsen-op-naam',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['culture', 'music', 'heritage', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
    priority: 'high',
  },
  {
    id: 'cultuurfonds-muziek',
    name: 'Cultuurfonds — Muzieksubsidies',
    url: 'https://www.cultuurfonds.nl/aanvragen/muziek',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['music', 'performing-arts'],
    scrapeMethod: 'html',
    enabled: true,
    priority: 'high',
  },
  {
    id: 'cultuurfonds-podiumkunsten',
    name: 'Cultuurfonds — Podiumkunsten',
    url: 'https://www.cultuurfonds.nl/aanvragen/podiumkunsten',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['performing-arts', 'theater', 'dance'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== DUTCH PRIVATE FOUNDATIONS (Vermogensfondsen) =====
  {
    id: 'koningin-juliana-fonds',
    name: 'Koningin Juliana Fonds',
    url: 'https://www.koningin-juliana-fonds.nl/aanvragen/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['social', 'health', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'stichting-dioraphte',
    name: 'Stichting Dioraphte',
    url: 'https://www.dioraphte.nl/aanvragen/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['culture', 'science', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'janivo-stichting',
    name: 'Janivo Stichting',
    url: 'https://www.janivostichting.nl/wat-we-doen/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['youth', 'culture', 'social'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'rc-maagdenhuis',
    name: 'R.C. Maagdenhuis',
    url: 'https://www.rcmaagdenhuis.nl/wat-wij-doen/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['social', 'youth', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'stichting-zabawas',
    name: 'Stichting Zabawas',
    url: 'https://www.zabawas.nl/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['social', 'culture', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'lira-fonds',
    name: 'Lira Fonds',
    url: 'https://www.lfrfrg.nl/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['literature', 'culture', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'kf-hein-fonds',
    name: 'K.F. Hein Fonds',
    url: 'https://www.kfheinfonds.nl/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['culture', 'arts', 'heritage'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'elise-mathilde-fonds',
    name: 'Elise Mathilde Fonds',
    url: 'https://www.elisemathilde.nl/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['culture', 'social', 'innovation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'ars-donandi',
    name: 'Ars Donandi',
    url: 'https://www.arsdonandi.nl/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['culture', 'heritage', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'stichting-de-hoge-dennen',
    name: 'Stichting de Hoge Dennen',
    url: 'https://www.hogedennen.nl/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['nature', 'environment', 'sustainability'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'stichting-de-zaaier',
    name: 'Stichting De Zaaier',
    url: 'https://www.stichtingdezaaier.nl/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['social', 'poverty', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'snf',
    name: 'Stichting Nationale Fondsen (SNF)',
    url: 'https://www.stichtingnationalefondsen.nl/',
    type: 'aggregator',
    region: 'Netherlands',
    categories: ['all'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== ALL 12 PROVINCIAL SUBSIDY PORTALS =====
  {
    id: 'provincie-friesland',
    name: 'Provinsje Fryslân — Subsidies',
    url: 'https://www.fryslan.frl/subsidies',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'community', 'environment', 'innovation'],
    scrapeMethod: 'html',
    enabled: true,
    priority: 'high',
  },
  {
    id: 'provincie-groningen',
    name: 'Provincie Groningen — Subsidies',
    url: 'https://www.provinciegroningen.nl/subsidies/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'community', 'environment'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'provincie-drenthe',
    name: 'Provincie Drenthe — Subsidies',
    url: 'https://www.provincie.drenthe.nl/subsidies/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'community', 'environment'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'provincie-overijssel',
    name: 'Provincie Overijssel — Subsidies',
    url: 'https://www.overijssel.nl/subsidies/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'community', 'innovation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'provincie-flevoland',
    name: 'Provincie Flevoland — Subsidies',
    url: 'https://www.flevoland.nl/subsidies/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'community', 'innovation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'provincie-gelderland',
    name: 'Provincie Gelderland — Subsidies',
    url: 'https://www.gelderland.nl/subsidies/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'community', 'environment'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'provincie-utrecht',
    name: 'Provincie Utrecht — Subsidies',
    url: 'https://www.provincie-utrecht.nl/subsidies/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'community', 'innovation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'provincie-noord-holland',
    name: 'Provincie Noord-Holland — Subsidies',
    url: 'https://www.noord-holland.nl/subsidies/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'community', 'environment'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'provincie-zuid-holland',
    name: 'Provincie Zuid-Holland — Subsidies',
    url: 'https://www.zuid-holland.nl/subsidies/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'community', 'innovation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'provincie-zeeland',
    name: 'Provincie Zeeland — Subsidies',
    url: 'https://www.zeeland.nl/subsidies/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'community', 'environment'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'provincie-noord-brabant',
    name: 'Provincie Noord-Brabant — Subsidies',
    url: 'https://www.brabant.nl/subsidy/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'community', 'innovation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'provincie-limburg',
    name: 'Provincie Limburg — Subsidies',
    url: 'https://www.limburg.nl/subsidies/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'community', 'environment'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== MAJOR DUTCH MUNICIPAL CULTURE PORTALS =====
  {
    id: 'gemeente-amsterdam-cultuur',
    name: 'Gemeente Amsterdam — Cultuur Subsidies',
    url: 'https://www.amsterdam.nl/subsidies/subsidies-cultuur/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'music', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'gemeente-rotterdam-cultuur',
    name: 'Gemeente Rotterdam — Cultuur Subsidies',
    url: 'https://www.rotterdam.nl/subsidies-cultuur/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'music', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'gemeente-den-haag-cultuur',
    name: 'Gemeente Den Haag — Cultuur',
    url: 'https://www.denhaag.nl/nl/subsidies/subsidies-kunst-en-cultuur/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'music', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'gemeente-utrecht-cultuur',
    name: 'Gemeente Utrecht — Cultuur',
    url: 'https://www.utrecht.nl/subsidie/cultuur/',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'music', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'gemeente-groningen-cultuur',
    name: 'Gemeente Groningen — Cultuur',
    url: 'https://gemeente.groningen.nl/subsidies-cultuur-en-evenementen',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'events', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'gemeente-leeuwarden-cultuur',
    name: 'Gemeente Leeuwarden — Cultuur',
    url: 'https://www.leeuwarden.nl/nl/subsidies',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'community'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'gemeente-weststellingwerf',
    name: 'Gemeente Weststellingwerf — Subsidies',
    url: 'https://www.weststellingwerf.nl/subsidies',
    type: 'government',
    region: 'Netherlands',
    categories: ['community', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
    priority: 'high',
  },

  // ===== DUTCH DEVELOPMENT & INTERNATIONAL =====
  {
    id: 'buza-subsidies',
    name: 'Ministerie BuZa — Subsidies Ontwikkelingssamenwerking',
    url: 'https://www.rijksoverheid.nl/onderwerpen/ontwikkelingssamenwerking/subsidies',
    type: 'government',
    region: 'Netherlands',
    categories: ['development', 'international', 'sustainability'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'nuffic',
    name: 'Nuffic — Internationalisering Onderwijs',
    url: 'https://www.nuffic.nl/programmas',
    type: 'government',
    region: 'Netherlands',
    categories: ['education', 'international', 'exchange'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'dutch-culture',
    name: 'DutchCulture — Internationalisering Cultuur',
    url: 'https://dutchculture.nl/nl/funding',
    type: 'government',
    region: 'Netherlands',
    categories: ['culture', 'international', 'exchange', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== DUTCH NATURE & ENVIRONMENT =====
  {
    id: 'postcode-loterij-fonds',
    name: 'Nationale Postcode Loterij — Goede Doelen',
    url: 'https://www.postcodeloterij.nl/goede-doelen',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['environment', 'social', 'culture', 'development'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'wwf-nl',
    name: 'WWF Nederland',
    url: 'https://www.wwf.nl/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['environment', 'biodiversity', 'nature'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'iucn-nl',
    name: 'IUCN NL',
    url: 'https://www.iucn.nl/en/programmes/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['environment', 'indigenous', 'conservation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'both-ends',
    name: 'Both ENDS',
    url: 'https://www.bothends.org/en/',
    type: 'foundation',
    region: 'Netherlands',
    categories: ['environment', 'rights', 'development'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ============================================
  // ===== EXPANDED EU SOURCES =================
  // ============================================
  {
    id: 'culture-moves-europe',
    name: 'Culture Moves Europe (EU Mobility)',
    url: 'https://culture.ec.europa.eu/funding/culture-moves-europe',
    type: 'government',
    region: 'Europe',
    categories: ['culture', 'arts', 'mobility', 'exchange'],
    scrapeMethod: 'html',
    enabled: true,
    priority: 'high',
  },
  {
    id: 'erasmus-plus',
    name: 'Erasmus+ Programme',
    url: 'https://erasmus-plus.ec.europa.eu/opportunities',
    type: 'government',
    region: 'Europe',
    categories: ['education', 'youth', 'sport', 'exchange'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'life-programme',
    name: 'LIFE Programme (Environment)',
    url: 'https://cinea.ec.europa.eu/programmes/life_en',
    type: 'government',
    region: 'Europe',
    categories: ['environment', 'climate', 'nature'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'esf-plus',
    name: 'European Social Fund Plus (ESF+)',
    url: 'https://ec.europa.eu/european-social-fund-plus/',
    type: 'government',
    region: 'Europe',
    categories: ['social', 'employment', 'inclusion'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'interreg-nwe',
    name: 'Interreg North-West Europe',
    url: 'https://www.nweurope.eu/calls/',
    type: 'government',
    region: 'Europe',
    categories: ['innovation', 'sustainability', 'cooperation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'european-cultural-foundation',
    name: 'European Cultural Foundation',
    url: 'https://culturalfoundation.eu/grants/',
    type: 'foundation',
    region: 'Europe',
    categories: ['culture', 'exchange', 'democracy'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'europa-nostra',
    name: 'Europa Nostra — Heritage Awards',
    url: 'https://www.europanostra.org/our-work/heritage-awards/',
    type: 'foundation',
    region: 'Europe',
    categories: ['heritage', 'culture', 'preservation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'compagnia-san-paolo',
    name: 'Compagnia di San Paolo',
    url: 'https://www.compagniadisanpaolo.it/en/calls-for-proposals/',
    type: 'foundation',
    region: 'Europe',
    categories: ['culture', 'social', 'innovation'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'mercator-stiftung',
    name: 'Stiftung Mercator',
    url: 'https://www.stiftung-mercator.de/en/what-we-do/',
    type: 'foundation',
    region: 'Europe',
    categories: ['culture', 'education', 'climate'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'robert-bosch-stiftung',
    name: 'Robert Bosch Stiftung',
    url: 'https://www.bosch-stiftung.de/en/funding',
    type: 'foundation',
    region: 'Europe',
    categories: ['sustainability', 'society', 'health', 'education'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== INTERNATIONAL MUSIC & ARTS =====
  {
    id: 'prs-foundation',
    name: 'PRS Foundation (UK Music)',
    url: 'https://prsfoundation.com/funding-support/',
    type: 'foundation',
    region: 'UK',
    categories: ['music', 'artists', 'talent'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'european-music-council',
    name: 'European Music Council',
    url: 'https://www.emc-imc.org/',
    type: 'foundation',
    region: 'Europe',
    categories: ['music', 'culture', 'exchange'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'on-the-move',
    name: 'On the Move — Cultural Mobility',
    url: 'https://on-the-move.org/funding',
    type: 'aggregator',
    region: 'Europe',
    categories: ['arts', 'mobility', 'culture', 'music'],
    scrapeMethod: 'html',
    enabled: true,
    priority: 'high',
  },
  {
    id: 'music-fund',
    name: 'Music Fund',
    url: 'https://www.musicfund.eu/',
    type: 'foundation',
    region: 'Europe',
    categories: ['music', 'instruments', 'education'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'goethe-institut',
    name: 'Goethe-Institut — Förderung',
    url: 'https://www.goethe.de/en/uun/auf.html',
    type: 'government',
    region: 'Europe',
    categories: ['culture', 'exchange', 'arts'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'arts-council-england',
    name: 'Arts Council England',
    url: 'https://www.artscouncil.org.uk/funding',
    type: 'government',
    region: 'UK',
    categories: ['arts', 'culture', 'music'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'swedish-arts-council',
    name: 'Swedish Arts Council (Kulturrådet)',
    url: 'https://www.kulturradet.se/en/funding/',
    type: 'government',
    region: 'Europe',
    categories: ['culture', 'arts', 'music'],
    scrapeMethod: 'html',
    enabled: true,
  },

  // ===== INTERNATIONAL INDIGENOUS & ENVIRONMENT =====
  {
    id: 'fpp-forest-peoples',
    name: 'Forest Peoples Programme',
    url: 'https://www.forestpeoples.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'forest', 'rights'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'iif-indigenous',
    name: 'International Indigenous Fund',
    url: 'https://internationalindigenousfund.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['indigenous', 'rights', 'culture'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'global-greengrants',
    name: 'Global Greengrants Fund',
    url: 'https://www.greengrants.org/grants/',
    type: 'foundation',
    region: 'Global',
    categories: ['environment', 'indigenous', 'grassroots'],
    scrapeMethod: 'html',
    enabled: true,
  },
  {
    id: 'thousand-currents',
    name: 'Thousand Currents',
    url: 'https://thousandcurrents.org/',
    type: 'foundation',
    region: 'Global',
    categories: ['food', 'indigenous', 'climate', 'grassroots'],
    scrapeMethod: 'html',
    enabled: true,
  },
]

// Categories that Sacred Foundation focuses on
export const relevantCategories = [
  'indigenous',
  'culture',
  'heritage',
  'food',
  'agriculture',
  'sustainability',
  'environment',
  'social enterprise',
  'community',
  'wellbeing',
  'research',
  'music',
  'performing-arts',
  'film',
  'documentary',
]

// Region priority for discovery — NL first, then EU, then global
export const regionPriority = [
  'Netherlands',
  'Europe',
  'UK',
  'Switzerland',
  'Global',
  'Australia',
  'Latin America',
  'Peru',
  'USA',
]

// Get sources sorted by region priority, with high-priority sources first within each region
export function getSortedSources() {
  const sorted = [...grantSources].filter(s => s.enabled)
  sorted.sort((a, b) => {
    const aPriority = a.priority === 'high' ? -1 : 0
    const bPriority = b.priority === 'high' ? -1 : 0
    if (aPriority !== bPriority) return aPriority - bPriority

    const aRegion = regionPriority.indexOf(a.region)
    const bRegion = regionPriority.indexOf(b.region)
    const aIdx = aRegion === -1 ? 999 : aRegion
    const bIdx = bRegion === -1 ? 999 : bRegion
    return aIdx - bIdx
  })
  return sorted
}

// Get sources filtered by region
export function getSourcesByRegion(region) {
  return grantSources.filter(s => s.enabled && s.region === region)
}
