// All grants data with regions and enhanced metadata
export const grants = [
  // 🇦🇺 AUSTRALIA - PTY LTD ELIGIBLE
  {
    id: 'dfat-acdgp',
    name: 'DFAT ACDGP Cultural Diplomacy',
    region: 'au',
    category: 'pty-ltd',
    grantCategory: 'cultural',
    amount: { min: 10000, max: 60000, display: '$10K-$60K' },
    deadline: '2026-02-06',
    deadlineDisplay: '6 Feb 2026',
    urgency: 'urgent',
    entityType: 'Pty Ltd',
    description: 'Australia\'s Cultural Diplomacy Grants Program supports cultural and artistic collaborations between Australia and other countries.',
    whySacredFits: 'Sacred\'s Ashaninka partnership in Peru demonstrates genuine cross-cultural collaboration. The ceremonial cacao work bridges Australian and Peruvian indigenous traditions.',
    eligibility: [
      'Australian registered business (ABN)',
      'Project involves cultural exchange with another country',
      'Demonstrates public diplomacy benefit for Australia',
      'Must be delivered within 12 months of funding'
    ],
    actionRequired: 'PRIORITY - Prepare application showcasing Ashaninka partnership and cultural diplomacy angle',
    applyUrl: 'https://www.dfat.gov.au/people-to-people/public-diplomacy/acdgp',
    sourceUrl: 'https://www.dfat.gov.au/people-to-people/foundations-councils-institutes',
    tags: ['cultural', 'international', 'peru', 'priority'],
    addedDate: '2026-01-15',
    isNew: false
  },
  {
    id: 'coles-nurture',
    name: 'Coles Nurture Fund Round 14',
    region: 'au',
    category: 'pty-ltd',
    grantCategory: 'food',
    amount: { min: 25000, max: 500000, display: 'Up to $500K' },
    deadline: '2026-02-13',
    deadlineDisplay: '13 Feb 2026',
    urgency: 'urgent',
    entityType: 'Pty Ltd',
    description: 'Supports Australian food and grocery producers to innovate, grow and create jobs. Focuses on sustainability and innovation.',
    whySacredFits: 'Sacred sources ceremonial cacao from Peru - a unique Australian importer. The sustainable sourcing model and ethical supply chain align with Coles\' values.',
    eligibility: [
      'Australian registered business',
      'Food/grocery producer or supplier',
      'Demonstrate innovation or sustainability',
      'Audited financial statements required',
      'Must show growth potential and job creation'
    ],
    actionRequired: 'Compile audited financials and prepare innovation/sustainability pitch',
    applyUrl: 'https://www.coles.com.au/about-coles/community/nurture-fund',
    sourceUrl: 'https://www.coles.com.au/about-coles/community/nurture-fund',
    tags: ['food', 'sustainability', 'large-grant', 'priority'],
    addedDate: '2026-01-10',
    isNew: false
  },
  {
    id: 'austrade-emdg',
    name: 'Austrade EMDG',
    region: 'au',
    category: 'pty-ltd',
    grantCategory: 'export',
    amount: { min: 40000, max: 160000, display: '$40K-$160K/yr' },
    deadline: 'rolling',
    deadlineDisplay: 'Rolling',
    urgency: 'medium',
    entityType: 'Pty Ltd',
    description: 'Export Market Development Grant reimburses up to 50% of eligible export marketing expenses for small-medium businesses.',
    whySacredFits: 'Sacred is expanding to EU markets and incurs significant export marketing costs. These expenses can be partially reimbursed.',
    eligibility: [
      'Australian business with turnover under $50M',
      'Exporting or planning to export',
      'Minimum $15,000 eligible expenses',
      'Products/services substantially Australian'
    ],
    actionRequired: 'Document all EU export marketing expenses for reimbursement claim',
    applyUrl: 'https://www.austrade.gov.au/australian/export/export-grants/emdg',
    sourceUrl: 'https://www.austrade.gov.au/en/how-we-can-help-you/grants-funding-assistance',
    tags: ['export', 'marketing', 'reimbursement', 'eu'],
    addedDate: '2026-01-01',
    isNew: false
  },
  {
    id: 'creative-australia-arts',
    name: 'Creative Australia Arts Projects',
    region: 'au',
    category: 'individual',
    grantCategory: 'arts',
    amount: { min: 10000, max: 100000, display: '$10K-$100K' },
    deadline: '2026-03-03',
    deadlineDisplay: '3 Mar 2026',
    urgency: 'high',
    entityType: 'Individual/NFP',
    description: 'Supports creation and presentation of new Australian artistic work across all art forms.',
    whySacredFits: 'Individual artists/musicians could apply for ceremony-related artistic projects.',
    eligibility: [
      'Australian artist or arts organisation',
      'Specific artistic project',
      'Public outcome (performance, exhibition, etc.)',
      'Quality artistic track record'
    ],
    actionRequired: 'Prepare individual artist applications for musicians/facilitators',
    applyUrl: 'https://creative.gov.au/funding-and-support/arts-projects/',
    sourceUrl: 'https://creative.australia.gov.au/funding',
    tags: ['individual', 'arts', 'creative-australia'],
    addedDate: '2026-01-01',
    isNew: false
  },
  {
    id: 'screen-australia-documentary',
    name: 'Screen Australia Documentary',
    region: 'au',
    category: 'pty-ltd',
    grantCategory: 'documentary',
    amount: { min: 25000, max: 250000, display: '$25K-$250K' },
    deadline: '2026-04-15',
    deadlineDisplay: '15 Apr 2026',
    urgency: 'medium',
    entityType: 'Pty Ltd',
    description: 'Supports Australian documentary filmmakers to develop and produce documentary projects.',
    whySacredFits: 'Perfect for documenting the Ashaninka cacao story, Sacred\'s journey, or ceremony practices.',
    eligibility: [
      'Australian production company',
      'Australian documentary project',
      'Creative team attached',
      'Distribution strategy'
    ],
    actionRequired: 'Develop documentary treatment for Ashaninka/cacao story',
    applyUrl: 'https://www.screenaustralia.gov.au/funding/documentary',
    sourceUrl: 'https://www.screenaustralia.gov.au/funding',
    tags: ['documentary', 'film', 'storytelling'],
    addedDate: '2026-01-20',
    isNew: true
  },
  {
    id: 'ian-potter-foundation',
    name: 'Ian Potter Foundation',
    region: 'au',
    category: 'nfp',
    grantCategory: 'arts',
    amount: { min: 20000, max: 200000, display: '$20K-$200K' },
    deadline: '2026-02-17',
    deadlineDisplay: '17 Feb - 12 Mar 2026',
    urgency: 'high',
    entityType: 'NFP',
    description: 'Major philanthropic foundation supporting arts, environment, health, education and community wellbeing.',
    whySacredFits: 'Sacred\'s community wellbeing and cultural work aligns well. Requires completed Dutch Stichting with DGR status.',
    eligibility: [
      'DGR Item 1 status required',
      'ACNC registered charity',
      'Strong governance and financials',
      'Clear community benefit'
    ],
    actionRequired: 'Requires Stichting completion - accelerate Dutch NFP setup',
    applyUrl: 'https://www.ianpotter.org.au/',
    sourceUrl: 'https://www.ianpotter.org.au',
    tags: ['nfp', 'major', 'foundation', 'dgr-required'],
    addedDate: '2026-01-01',
    isNew: false
  },
  {
    id: 'coalar',
    name: 'COALAR Grants Round',
    region: 'au',
    category: 'pty-ltd',
    grantCategory: 'cultural',
    amount: { min: 10000, max: 50000, display: '$10K-$50K' },
    deadline: '2026-08-01',
    deadlineDisplay: 'Aug 2026',
    urgency: 'medium',
    entityType: 'Pty Ltd',
    description: 'Council on Australia Latin America Relations supports projects strengthening ties between Australia and Latin America.',
    whySacredFits: 'PERFECT FIT - Sacred\'s Peru partnership with Ashaninka communities is exactly what this program supports.',
    eligibility: [
      'Australian organisation',
      'Project involves Latin American countries',
      'Demonstrates mutual benefit',
      'Cultural, educational or business exchange'
    ],
    actionRequired: 'PRIORITY - Begin developing Peru cultural exchange project proposal',
    applyUrl: 'https://www.dfat.gov.au/people-to-people/foundations-councils-institutes/coalar',
    sourceUrl: 'https://www.dfat.gov.au/people-to-people/foundations-councils-institutes',
    tags: ['peru', 'latin-america', 'cultural', 'priority'],
    addedDate: '2026-01-01',
    isNew: false
  },
  {
    id: 'city-melbourne',
    name: 'City of Melbourne Business Growth',
    region: 'au',
    category: 'pty-ltd',
    grantCategory: 'social-enterprise',
    amount: { min: 5000, max: 30000, display: 'Up to $30K' },
    deadline: '2026-10-01',
    deadlineDisplay: 'Oct 2026',
    urgency: 'low',
    entityType: 'Pty Ltd',
    description: 'Supports Melbourne-based small businesses to grow, innovate and create employment. Includes Social Impact stream.',
    whySacredFits: 'Sacred operates in Melbourne and has strong social impact through ethical sourcing and community ceremony work.',
    eligibility: [
      'Business located in City of Melbourne',
      'Trading for at least 12 months',
      'Fewer than 20 employees',
      'Demonstrate growth potential'
    ],
    actionRequired: 'Document social impact metrics for Social Impact stream',
    applyUrl: 'https://www.melbourne.vic.gov.au/business/grants-tenders/small-business-grants',
    sourceUrl: 'https://www.melbourne.vic.gov.au/community/grants-and-sponsorships',
    tags: ['melbourne', 'social-impact', 'local'],
    addedDate: '2026-01-01',
    isNew: false
  },
  {
    id: 'westfield-heroes',
    name: 'Westfield Local Heroes',
    region: 'au',
    category: 'nomination',
    grantCategory: 'social-enterprise',
    amount: { min: 5000, max: 20000, display: '$5K-$20K' },
    deadline: '2026-03-12',
    deadlineDisplay: '12 Mar 2026',
    urgency: 'high',
    entityType: 'Nomination',
    description: 'Recognises community heroes making a difference. Public nomination and voting.',
    whySacredFits: 'Sacred founder/key facilitator could be nominated for community contribution.',
    eligibility: [
      'Individual making community difference',
      'Near a Westfield centre',
      'Third party nomination',
      'Public voting component'
    ],
    actionRequired: 'Identify which Westfield centre is closest, prepare nomination',
    applyUrl: 'https://www.westfield.com.au/local-heroes',
    sourceUrl: 'https://www.westfield.com.au/local-heroes',
    tags: ['nomination', 'community', 'individual'],
    addedDate: '2026-01-01',
    isNew: false
  },

  // 🇳🇱 NETHERLANDS - URGENT DEADLINES
  {
    id: 'culture-health-call',
    name: 'Culture & Health Call',
    region: 'nl',
    category: 'nfp',
    grantCategory: 'health',
    amount: { min: 8000, max: 8000, display: '€8,000' },
    deadline: '2026-02-02',
    deadlineDisplay: '2 Feb 2026 (Stage 1)',
    urgency: 'urgent',
    entityType: 'NFP/Stichting',
    description: 'EU co-funded program for artist-healthcare partnerships promoting mental health. Stage 2 deadline: March 30.',
    whySacredFits: 'PERFECT - ceremonies in clinical settings, wellbeing outcomes. Partner with burnout clinic or trauma center.',
    eligibility: [
      'Dutch mental health organization partner required',
      'Artist-healthcare collaboration',
      'Mental health focus',
      'Measurable wellbeing outcomes'
    ],
    actionRequired: 'URGENT - Prepare Stage 1 EOI, find Dutch mental health partner (burnout clinic, trauma center)',
    applyUrl: 'https://cultureandhealth.eu',
    sourceUrl: 'https://cultureandhealth.eu',
    tags: ['health', 'mental-health', 'urgent', 'stichting', 'priority'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'idfa-bertha-fund',
    name: 'IDFA Bertha Fund',
    region: 'nl',
    category: 'nfp',
    grantCategory: 'documentary',
    amount: { min: 10000, max: 25000, display: '€25,000' },
    deadline: '2026-02-10',
    deadlineDisplay: '10 Feb 2026',
    urgency: 'urgent',
    entityType: 'Stichting',
    description: 'Amsterdam documentary film festival fund supporting documentary development and production.',
    whySacredFits: 'Perfect for documentary about Ashaninka partnership, ceremonial practices, or cacao journey.',
    eligibility: [
      'Documentary project',
      'Professional filmmaker/team',
      'Social impact story',
      'International co-production potential'
    ],
    actionRequired: 'URGENT - Prepare documentary treatment for Ashaninka/cacao story',
    applyUrl: 'https://www.idfa.nl/en/info/idfa-bertha-fund',
    sourceUrl: 'https://www.idfa.nl/en/info/idfa-bertha-fund',
    tags: ['documentary', 'film', 'urgent', 'stichting'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'cultuurparticipatie-cocreation',
    name: 'Fonds voor Cultuurparticipatie - Co-creation',
    region: 'nl',
    category: 'nfp',
    grantCategory: 'cultural',
    amount: { min: 2500, max: 500000, display: '€2.5K-€500K' },
    deadline: '2026-12-09',
    deadlineDisplay: 'Open Jan 12 - Dec 9, 2026',
    urgency: 'high',
    entityType: 'NFP/Stichting',
    description: 'Cultural participation, intangible heritage, heritage volunteers, cultural education. Co-creation focus.',
    whySacredFits: 'EXCELLENT - Intangible heritage (ceremonies), community co-creation, cultural participation.',
    eligibility: [
      'Cultural participation project',
      'Intangible heritage focus',
      'Community involvement',
      'Co-creation methodology'
    ],
    actionRequired: 'Prepare application for intangible heritage / ceremony co-creation project',
    applyUrl: 'https://cultuurparticipatie.nl/subsidies',
    sourceUrl: 'https://cultuurparticipatie.nl',
    tags: ['heritage', 'participation', 'co-creation', 'stichting'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'mondriaan-residency',
    name: 'Mondriaan Fund - Residency',
    region: 'nl',
    category: 'individual',
    grantCategory: 'arts',
    amount: { min: 1500, max: 20000, display: '€1.5K-€20K' },
    deadline: '2026-02-26',
    deadlineDisplay: '26 Feb 2026',
    urgency: 'urgent',
    entityType: 'Individual/Stichting',
    description: 'Artist residency grants for visual artists and cultural heritage professionals.',
    whySacredFits: 'Support for facilitators/artists to develop ceremony-related visual/heritage work.',
    eligibility: [
      'Visual artist or heritage professional',
      'Residency program',
      'Professional development focus',
      'Clear artistic outcome'
    ],
    actionRequired: 'Identify residency opportunity and prepare application',
    applyUrl: 'https://www.mondriaanfonds.nl/en/grants/',
    sourceUrl: 'https://www.mondriaanfonds.nl/en/',
    tags: ['residency', 'arts', 'individual', 'urgent'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'stimuleringsfonds-activities',
    name: 'Stimuleringsfonds - Activities Programme',
    region: 'nl',
    category: 'nfp',
    grantCategory: 'arts',
    amount: { min: 50000, max: 125000, display: '€125K/year' },
    deadline: '2026-02-28',
    deadlineDisplay: 'Late Feb 2026',
    urgency: 'urgent',
    entityType: 'NFP/Stichting',
    description: '€20M annual fund for design, architecture, digital culture. Round 1 deadline late February.',
    whySacredFits: 'Digital ceremonies, ceremony space design, sustainable architecture projects.',
    eligibility: [
      'Design/architecture/digital project',
      'Innovation focus',
      'Professional practice',
      'Multi-year activities possible'
    ],
    actionRequired: 'URGENT - Prepare application for Round 1 deadline',
    applyUrl: 'https://stimuleringsfonds.nl/en/grants/',
    sourceUrl: 'https://stimuleringsfonds.nl/en/',
    tags: ['design', 'digital', 'architecture', 'urgent', 'stichting'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'spvo-supply-chain',
    name: 'SPVO - Responsible Business',
    region: 'nl',
    category: 'nfp',
    grantCategory: 'indigenous',
    amount: { min: 50000, max: 500000, display: '€50K-€500K (€5.7M pool)' },
    deadline: '2026-03-16',
    deadlineDisplay: '16 Mar 2026 (Quick Scan)',
    urgency: 'urgent',
    entityType: 'NL Entity',
    description: 'Dutch government fund for international value chains, Indigenous rights, fair trade. €4.3M reserved for SME partnerships.',
    whySacredFits: 'PERFECT for Ashaninka partnership, cultural exchange, fair trade cacao sourcing.',
    eligibility: [
      'International value chain project',
      'Indigenous rights or fair trade focus',
      'Dutch entity (SME or Stichting)',
      'Supply chain improvement'
    ],
    actionRequired: 'PRIORITY - Submit Quick Scan by Mar 16, Full Application by Apr 13',
    applyUrl: 'https://english.rvo.nl/subsidies-financing/spvo',
    sourceUrl: 'https://english.rvo.nl/subsidies-financing/spvo',
    tags: ['supply-chain', 'indigenous', 'fair-trade', 'urgent', 'priority', 'large-grant'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'fonds-podiumkunsten',
    name: 'Fonds Podiumkunsten',
    region: 'nl',
    category: 'nfp',
    grantCategory: 'performing-arts',
    amount: { min: 25000, max: 1000000, display: '€75K-€1M+' },
    deadline: '2026-04-01',
    deadlineDisplay: '1 Apr 2026 (Round 2)',
    urgency: 'high',
    entityType: 'NFP/Stichting',
    description: 'Professional music, theatre, dance, festivals. International co-productions €1,070,000/round.',
    whySacredFits: 'EXCELLENT - Festivals, ceremonies as performance, international co-productions.',
    eligibility: [
      'Professional performing arts',
      'Festival or performance project',
      'International co-production possible',
      'Clear public presentation'
    ],
    actionRequired: 'Prepare festival/performance application for Round 2',
    applyUrl: 'https://fondspodiumkunsten.nl/en/',
    sourceUrl: 'https://fondspodiumkunsten.nl/en/',
    tags: ['performing-arts', 'festival', 'music', 'stichting', 'large-grant'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'mondriaan-fund',
    name: 'Mondriaan Fund - International Projects',
    region: 'nl',
    category: 'nfp',
    grantCategory: 'arts',
    amount: { min: 5000, max: 75000, display: '€5K-€75K' },
    deadline: '2026-03-15',
    deadlineDisplay: '15 Mar 2026',
    urgency: 'high',
    entityType: 'NFP/Stichting',
    description: 'Dutch cultural fund supporting visual arts, heritage, and international cultural exchange. €35M annual budget.',
    whySacredFits: 'Perfect for Sacred\'s Dutch Stichting to fund international cultural projects linking NL-Peru-Australia.',
    eligibility: [
      'Dutch-based cultural organisation',
      'International cultural project',
      'Professional artistic practice',
      'Clear public outcome'
    ],
    actionRequired: 'Prepare application once Stichting is operational',
    applyUrl: 'https://www.mondriaanfonds.nl/en/grants/',
    sourceUrl: 'https://www.mondriaanfonds.nl/en/',
    tags: ['dutch', 'arts', 'international', 'stichting'],
    addedDate: '2026-01-22',
    isNew: true
  },
  {
    id: 'doen-foundation',
    name: 'DOEN Foundation',
    region: 'nl',
    category: 'nfp',
    grantCategory: 'social-enterprise',
    amount: { min: 10000, max: 100000, display: '€10K-€100K (€25M+ annual)' },
    deadline: 'rolling',
    deadlineDisplay: 'Rolling (4-month processing)',
    urgency: 'high',
    entityType: 'NFP/Stichting',
    description: 'Supports pioneers in sustainable, social and cultural innovation. Focus on regenerative economy. Also offers loans via DOEN Ventures.',
    whySacredFits: 'EXCELLENT - Social practice art, radical imagination, inclusive cooperation. Sacred\'s ethical cacao sourcing and regenerative approach aligns perfectly.',
    eligibility: [
      'Innovative social/sustainable project',
      'Pioneer organization',
      'Clear theory of change',
      'Scalable impact model'
    ],
    actionRequired: 'Research DOEN\'s current priorities and prepare pitch',
    applyUrl: 'https://www.doen.nl/en/apply',
    sourceUrl: 'https://www.doen.nl/en',
    tags: ['dutch', 'social-enterprise', 'sustainability', 'pioneer', 'priority'],
    addedDate: '2026-01-22',
    isNew: true
  },
  {
    id: 'oranjefonds',
    name: 'Oranjefonds',
    region: 'nl',
    category: 'nfp',
    grantCategory: 'social-enterprise',
    amount: { min: 2500, max: 30000000, display: '€2.5K-€30M (8,500+ projects/yr)' },
    deadline: 'rolling',
    deadlineDisplay: 'Rolling',
    urgency: 'high',
    entityType: 'NFP/Stichting',
    description: 'Royal Patrons: King Willem-Alexander & Queen Máxima. Focus on social cohesion, participation, community.',
    whySacredFits: 'EXCELLENT - Ceremonies create connection, reduce isolation. Youth grants up to €2,500 available.',
    eligibility: [
      'Social cohesion project',
      'Community participation focus',
      'Dutch-based initiative',
      'Clear social impact'
    ],
    actionRequired: 'Prepare application focused on community connection through ceremonies',
    applyUrl: 'https://oranjefonds.nl',
    sourceUrl: 'https://oranjefonds.nl',
    tags: ['social-cohesion', 'community', 'royal', 'stichting'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'triodos-foundation',
    name: 'Triodos Foundation',
    region: 'nl',
    category: 'nfp',
    grantCategory: 'social-enterprise',
    amount: { min: 5000, max: 20000, display: '€5K-€20K' },
    deadline: 'rolling',
    deadlineDisplay: 'Rolling (no deadline)',
    urgency: 'medium',
    entityType: 'NFP/Stichting',
    description: 'Social innovation, nature/environment, people/society, international cooperation. NL-based non-profits.',
    whySacredFits: 'EXCELLENT - Community wellbeing, holistic education, nature connection.',
    eligibility: [
      'Social innovation project',
      'NL-based non-profit',
      'Nature or community focus',
      'Clear social benefit'
    ],
    actionRequired: 'Prepare application for community wellbeing project',
    applyUrl: 'https://triodos.com/regenerative-money-centre',
    sourceUrl: 'https://triodos.com/regenerative-money-centre',
    tags: ['social-innovation', 'nature', 'community', 'stichting'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'kansfonds',
    name: 'KansFonds',
    region: 'nl',
    category: 'nfp',
    grantCategory: 'social-enterprise',
    amount: { min: 5000, max: 50000, display: 'Varies' },
    deadline: 'rolling',
    deadlineDisplay: 'Rolling',
    urgency: 'medium',
    entityType: 'NFP/Stichting',
    description: 'Participation of vulnerable groups in society.',
    whySacredFits: 'EXCELLENT - Ceremonies for vulnerable populations, social inclusion.',
    eligibility: [
      'Focus on vulnerable groups',
      'Social participation',
      'Dutch-based project',
      'Clear inclusion outcomes'
    ],
    actionRequired: 'Develop proposal for ceremonies with vulnerable populations',
    applyUrl: 'https://kansfonds.nl',
    sourceUrl: 'https://kansfonds.nl',
    tags: ['vulnerable', 'inclusion', 'social', 'stichting'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'prins-bernhard',
    name: 'Prins Bernhard Cultuurfonds',
    region: 'nl',
    category: 'nfp',
    grantCategory: 'arts',
    amount: { min: 1500, max: 30000, display: '€1.5K-€30K (Charlotte Köhler Prize)' },
    deadline: 'rolling',
    deadlineDisplay: 'Rolling (8 weeks review)',
    urgency: 'medium',
    entityType: 'NFP/Stichting',
    description: '3,500+ projects/year. 12 provincial branches. Scholarships €1,500-€20,000. Charlotte Köhler Prize €30,000 for talent under 35.',
    whySacredFits: 'Cultural preservation, nature connection, facilitator training. Note: 3-year NL residency for non-Dutch.',
    eligibility: [
      'Dutch cultural/heritage project',
      'Clear cultural value',
      'Professional execution',
      'Public benefit'
    ],
    actionRequired: 'Identify Dutch cultural programming to propose',
    applyUrl: 'https://www.cultuurfonds.nl/en/application',
    sourceUrl: 'https://www.cultuurfonds.nl/en',
    tags: ['dutch', 'culture', 'heritage', 'scholarships'],
    addedDate: '2026-01-22',
    isNew: true
  },
  {
    id: 'creative-industries-fund-nl',
    name: 'Creative Industries Fund NL',
    region: 'nl',
    category: 'nfp',
    grantCategory: 'arts',
    amount: { min: 10000, max: 125000, display: '€10K-€125K/year' },
    deadline: '2026-02-28',
    deadlineDisplay: 'Late Feb 2026 (Round 1)',
    urgency: 'urgent',
    entityType: 'NFP/Stichting',
    description: '€20M annual. Design, architecture, digital culture. Supports cross-disciplinary creative projects.',
    whySacredFits: 'Digital ceremonies, ceremony space design, sustainable architecture.',
    eligibility: [
      'Creative industries project',
      'Innovation focus',
      'Dutch connection',
      'Professional practice'
    ],
    actionRequired: 'URGENT - Prepare application for Round 1 (late Feb deadline)',
    applyUrl: 'https://stimuleringsfonds.nl/en/grants/',
    sourceUrl: 'https://stimuleringsfonds.nl/en/',
    tags: ['dutch', 'creative', 'design', 'digital', 'urgent'],
    addedDate: '2026-01-22',
    isNew: true
  },

  // 🇪🇺 EU-WIDE
  {
    id: 'horizon-europe-ich',
    name: 'Horizon Europe - Intangible Cultural Heritage',
    region: 'eu',
    category: 'nfp',
    grantCategory: 'cultural',
    amount: { min: 3000000, max: 4000000, display: '€3-4M per project' },
    deadline: '2026-03-17',
    deadlineDisplay: '17 Mar 2026 (Stage 2)',
    urgency: 'urgent',
    entityType: 'NFP Consortium',
    description: 'Total pool €12M. Explicitly covers rituals, traditions, performing arts, mental health. Requires 3+ EU country consortium.',
    whySacredFits: 'EXCELLENT - ceremonies as ICH, traditional knowledge preservation, mental health outcomes.',
    eligibility: [
      'Consortium of 3+ EU countries',
      'Intangible cultural heritage focus',
      'Research/innovation project',
      'Large-scale impact'
    ],
    actionRequired: 'PRIORITY - Find consortium partners, prepare Stage 2 application',
    applyUrl: 'https://ec.europa.eu/info/funding-tenders',
    sourceUrl: 'https://ec.europa.eu/info/funding-tenders',
    tags: ['eu', 'heritage', 'research', 'large-grant', 'urgent', 'priority'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'culture-moves-europe-host',
    name: 'Culture Moves Europe - Host',
    region: 'eu',
    category: 'nfp',
    grantCategory: 'arts',
    amount: { min: 3000, max: 5000, display: '€3K-€5K' },
    deadline: '2026-03-16',
    deadlineDisplay: '16 Mar 2026',
    urgency: 'urgent',
    entityType: 'NFP/Stichting',
    description: 'Host grants for organizations receiving international artists for residencies.',
    whySacredFits: 'Support for hosting international facilitators/artists at Sacred events.',
    eligibility: [
      'Cultural organization',
      'Hosting international artists',
      'Residency program',
      'Clear cultural exchange'
    ],
    actionRequired: 'Apply as host organization for artist residencies',
    applyUrl: 'https://culture.ec.europa.eu/creative-europe/culture-moves-europe',
    sourceUrl: 'https://culture.ec.europa.eu/creative-europe/culture-moves-europe',
    tags: ['eu', 'residency', 'hosting', 'urgent', 'stichting'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'creative-europe-small',
    name: 'Creative Europe - Small Cooperation',
    region: 'eu',
    category: 'nfp',
    grantCategory: 'cultural',
    amount: { min: 60000, max: 200000, display: '€200K' },
    deadline: '2027-01-01',
    deadlineDisplay: '2027 (planning)',
    urgency: 'medium',
    entityType: 'NFP + 3 countries',
    description: 'EU flagship cultural funding. €2.44B total (2021-2027). Small-scale cooperation projects.',
    whySacredFits: 'Perfect for multi-country projects linking Sacred\'s NL and EU activities.',
    eligibility: [
      'EU-based cultural organisation',
      'Minimum 3 partners from 3 countries',
      'Cross-border cultural cooperation',
      'Track record required'
    ],
    actionRequired: 'Build consortium, establish track record for 2027 application',
    applyUrl: 'https://ec.europa.eu/programmes/creative-europe/culture/',
    sourceUrl: 'https://culture.ec.europa.eu/creative-europe',
    tags: ['eu', 'cultural', 'cooperation', 'large-grant'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'culture-moves-europe-individual',
    name: 'Culture Moves Europe - Individual',
    region: 'eu',
    category: 'individual',
    grantCategory: 'arts',
    amount: { min: 1000, max: 7000, display: '€1K-€7K each' },
    deadline: '2026-04-30',
    deadlineDisplay: '30 Apr 2026',
    urgency: 'high',
    entityType: 'Individual Artists',
    description: 'Mobility grants for artists (7-60 days). Architecture, heritage, design, music, performing arts, visual arts.',
    whySacredFits: 'Support Sacred\'s facilitators/artists to travel for cultural exchange within Europe.',
    eligibility: [
      'Artist or cultural professional',
      'Based in Creative Europe country',
      'International mobility project',
      'Professional development purpose'
    ],
    actionRequired: 'Identify mobility opportunities for multiple team members',
    applyUrl: 'https://culture.ec.europa.eu/creative-europe/culture-moves-europe',
    sourceUrl: 'https://culture.ec.europa.eu/creative-europe/culture-moves-europe',
    tags: ['eu', 'mobility', 'individual', 'travel'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'european-cultural-foundation',
    name: 'European Cultural Foundation (ECF)',
    region: 'eu',
    category: 'nfp',
    grantCategory: 'cultural',
    amount: { min: 5000, max: 10000, display: 'Up to €10K' },
    deadline: '2026-01-31',
    deadlineDisplay: 'Jan 2026 (Culture of Solidarity)',
    urgency: 'urgent',
    entityType: 'NFP',
    description: 'Amsterdam-based. Culture of Solidarity Fund, R&D Grants. Open calls January 2026.',
    whySacredFits: 'EXCELLENT - Cross-border cultural collaboration, social engagement.',
    eligibility: [
      'Cultural democracy focus',
      'Cross-border element',
      'Community engagement',
      'Inclusive practices'
    ],
    actionRequired: 'URGENT - Apply for Culture of Solidarity Fund (Jan deadline)',
    applyUrl: 'https://culturalfoundation.eu/grants/',
    sourceUrl: 'https://culturalfoundation.eu',
    tags: ['eu', 'cultural-democracy', 'community', 'urgent'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'effea-discovery',
    name: 'EFFEA - Discovery Grant',
    region: 'eu',
    category: 'nfp',
    grantCategory: 'performing-arts',
    amount: { min: 8000, max: 8000, display: '€8K (40 grants)' },
    deadline: '2026-10-01',
    deadlineDisplay: '~Oct 2026',
    urgency: 'medium',
    entityType: 'Festival Consortium',
    description: 'European Festivals Fund for Emerging Artists. Requires 3+ festivals from different countries. 80% for artist costs.',
    whySacredFits: 'Position Sacred events as festivals, partner with European festivals.',
    eligibility: [
      '3+ festivals from different countries',
      'Emerging artist focus',
      '80% budget for artists',
      'Festival partnership'
    ],
    actionRequired: 'Find 2+ European festival partners for consortium',
    applyUrl: 'https://effea.eu',
    sourceUrl: 'https://effea.eu',
    tags: ['eu', 'festival', 'emerging-artists', 'consortium'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'effea-springboard',
    name: 'EFFEA - Springboard Grant',
    region: 'eu',
    category: 'nfp',
    grantCategory: 'performing-arts',
    amount: { min: 15000, max: 15000, display: '€15K (10 grants)' },
    deadline: '2026-10-01',
    deadlineDisplay: '~Oct 2026',
    urgency: 'medium',
    entityType: 'Festival Consortium',
    description: 'European Festivals Fund higher tier. Requires 3+ festivals, more established artists.',
    whySacredFits: 'For more established Sacred festival programming.',
    eligibility: [
      '3+ festivals from different countries',
      'Established emerging artist',
      '80% budget for artists',
      'Stronger track record'
    ],
    actionRequired: 'Develop festival programming with European partners',
    applyUrl: 'https://effea.eu',
    sourceUrl: 'https://effea.eu',
    tags: ['eu', 'festival', 'springboard', 'consortium'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'eu4health',
    name: 'EU4Health - Mental Health',
    region: 'eu',
    category: 'nfp',
    grantCategory: 'health',
    amount: { min: 100000, max: 1000000, display: '€100K-€1M+' },
    deadline: '2026-06-01',
    deadlineDisplay: 'Jun 2026 (expected)',
    urgency: 'medium',
    entityType: 'NFP Consortium',
    description: '€5.3B (2021-2027). €1.23B mental health flagship. Prevention, community wellbeing interventions.',
    whySacredFits: 'EXCELLENT - Prevention-oriented mental health, community wellbeing interventions.',
    eligibility: [
      'Health-focused consortium',
      'Mental health prevention',
      'EU-wide impact',
      'Evidence-based approach'
    ],
    actionRequired: 'Research 2026 calls, build health sector partnerships',
    applyUrl: 'https://hadea.ec.europa.eu/programmes/eu4health',
    sourceUrl: 'https://hadea.ec.europa.eu/programmes/eu4health',
    tags: ['eu', 'health', 'mental-health', 'prevention', 'large-grant'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'cerv-citizens',
    name: 'CERV - Citizens Engagement',
    region: 'eu',
    category: 'nfp',
    grantCategory: 'social-enterprise',
    amount: { min: 100000, max: 500000, display: '€100K+ (Networks of Towns)' },
    deadline: '2026-04-01',
    deadlineDisplay: 'Apr 2026 (expected)',
    urgency: 'medium',
    entityType: 'NFP Network',
    description: '€1.55B (2021-2027). Town twinning, citizens engagement, democratic participation.',
    whySacredFits: 'Town twinning around ceremony/wellbeing, community engagement.',
    eligibility: [
      'Network of European towns',
      'Citizens engagement focus',
      'Cross-border cooperation',
      'Democratic participation'
    ],
    actionRequired: 'Research town twinning opportunities around ceremony/wellbeing',
    applyUrl: 'https://commission.europa.eu/funding-tenders',
    sourceUrl: 'https://commission.europa.eu/funding-tenders',
    tags: ['eu', 'citizens', 'towns', 'engagement'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'eit-culture-creativity',
    name: 'EIT Culture & Creativity',
    region: 'eu',
    category: 'nfp',
    grantCategory: 'arts',
    amount: { min: 50000, max: 350000, display: 'Up to €350K' },
    deadline: '2026-05-01',
    deadlineDisplay: 'May 2026 (expected)',
    urgency: 'medium',
    entityType: 'NFP',
    description: 'Short Innovation Projects up to 70% funding. Fashion, architecture, heritage, audiovisual, gaming. €7M total.',
    whySacredFits: 'Digital innovation (online ceremonies), heritage preservation.',
    eligibility: [
      'Innovation project',
      'Creative industries focus',
      'Technology integration',
      'Scalable impact'
    ],
    actionRequired: 'Explore digital ceremony innovation possibilities',
    applyUrl: 'https://eit-culture-creativity.eu',
    sourceUrl: 'https://eit-culture-creativity.eu',
    tags: ['eu', 'innovation', 'digital', 'creative'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'erasmus-adult-education',
    name: 'Erasmus+ Adult Education',
    region: 'eu',
    category: 'nfp',
    grantCategory: 'education',
    amount: { min: 30000, max: 150000, display: '€30K-€150K' },
    deadline: '2026-02-20',
    deadlineDisplay: 'Feb 2026 (expected)',
    urgency: 'high',
    entityType: 'NFP/Education',
    description: 'Adult education mobility, partnerships, professional development.',
    whySacredFits: 'Facilitator training as adult education, international exchanges.',
    eligibility: [
      'Adult education provider',
      'Professional development focus',
      'International partnership',
      'Structured curriculum'
    ],
    actionRequired: 'Position facilitator training as adult education program',
    applyUrl: 'https://erasmus-plus.ec.europa.eu',
    sourceUrl: 'https://erasmus-plus.ec.europa.eu',
    tags: ['eu', 'education', 'adult-learning', 'mobility'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'interreg-meuse-rhine',
    name: 'Interreg Meuse-Rhine',
    region: 'eu',
    category: 'nfp',
    grantCategory: 'cultural',
    amount: { min: 100000, max: 2000000, display: '€1-2M typical' },
    deadline: '2026-07-01',
    deadlineDisplay: 'Jul 2026 (5th call closes)',
    urgency: 'medium',
    entityType: 'Cross-border Consortium',
    description: 'NL-BE-DE tri-border region. Quality tourism, green society, health.',
    whySacredFits: 'EXCELLENT - Tri-border wellness tourism, health/nature projects.',
    eligibility: [
      'Cross-border NL-BE-DE project',
      'Health or tourism focus',
      'Green/sustainable approach',
      'Regional impact'
    ],
    actionRequired: 'Identify Belgian/German partners for wellness tourism project',
    applyUrl: 'https://interregmeuserhine.eu',
    sourceUrl: 'https://interregmeuserhine.eu',
    tags: ['eu', 'interreg', 'cross-border', 'tourism', 'health'],
    addedDate: '2026-01-28',
    isNew: true
  },

  // 🇵🇪 PERU / LATIN AMERICA & INDIGENOUS
  {
    id: 'prince-claus-seed',
    name: 'Prince Claus Seed Award',
    region: 'pe',
    category: 'nfp',
    grantCategory: 'indigenous',
    amount: { min: 5000, max: 5000, display: '€5,000 (100 grants)' },
    deadline: '2026-01-08',
    deadlineDisplay: '8 Jan 2026',
    urgency: 'urgent',
    entityType: 'NFP/Community',
    description: 'Amsterdam-based. Focus: culture in crisis, climate, free expression, structural equity. Africa, Asia, Latin America, Caribbean, Eastern Europe.',
    whySacredFits: 'EXCELLENT - Ashaninka partnership, cultural preservation under pressure.',
    eligibility: [
      'Cultural practitioner/organization',
      'Focus regions: Africa, Asia, LatAm, Caribbean',
      'Culture under pressure',
      'Innovative approach'
    ],
    actionRequired: 'Apply for Ashaninka cultural preservation project',
    applyUrl: 'https://princeclausfund.org',
    sourceUrl: 'https://princeclausfund.org',
    tags: ['indigenous', 'cultural', 'seed', 'amsterdam'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'prince-claus-impact',
    name: 'Prince Claus Impact Award',
    region: 'pe',
    category: 'nfp',
    grantCategory: 'indigenous',
    amount: { min: 50000, max: 100000, display: '€100K' },
    deadline: 'rolling',
    deadlineDisplay: 'Rolling (invitation)',
    urgency: 'medium',
    entityType: 'NFP/Community',
    description: 'Larger grants for proven cultural initiatives. By invitation or nomination.',
    whySacredFits: 'For established Ashaninka partnership with proven impact.',
    eligibility: [
      'Established cultural initiative',
      'Proven track record',
      'Scalable impact',
      'Nomination/invitation required'
    ],
    actionRequired: 'Build track record for future nomination',
    applyUrl: 'https://princeclausfund.org',
    sourceUrl: 'https://princeclausfund.org',
    tags: ['indigenous', 'cultural', 'impact', 'large-grant'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'cultural-survival-keepers',
    name: 'Cultural Survival - Keepers of the Earth Fund',
    region: 'pe',
    category: 'nfp',
    grantCategory: 'indigenous',
    amount: { min: 5000, max: 12000, display: 'Up to $12,000' },
    deadline: 'rolling',
    deadlineDisplay: 'Rolling',
    urgency: 'high',
    entityType: 'Indigenous Community',
    description: 'Grassroots Indigenous-led self-determined development projects. $2.2M+ granted to 392 projects in 40 countries.',
    whySacredFits: 'EXCELLENT - Direct support to Ashaninka community projects.',
    eligibility: [
      'Indigenous-led initiative',
      'Self-determined development',
      'Community-based project',
      'Grassroots approach'
    ],
    actionRequired: 'Support Ashaninka cooperative to apply directly',
    applyUrl: 'https://culturalsurvival.org/grantmaking',
    sourceUrl: 'https://culturalsurvival.org/grantmaking',
    tags: ['indigenous', 'grassroots', 'community', 'peru'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'mino-niibi-fund',
    name: 'Mino-Niibi Fund for Indigenous Cultures',
    region: 'pe',
    category: 'nfp',
    grantCategory: 'indigenous',
    amount: { min: 5000, max: 25000, display: 'Varies' },
    deadline: 'rolling',
    deadlineDisplay: 'Rolling',
    urgency: 'medium',
    entityType: 'Indigenous Community',
    description: 'The Cultural Conservancy. Indigenous-led organizations in Americas and Pacific. Cultural revitalization, language, foodways, youth-elder exchanges.',
    whySacredFits: 'EXCELLENT - Ashaninka cultural preservation, traditional foodways (cacao).',
    eligibility: [
      'Indigenous-led organization',
      'Americas or Pacific region',
      'Cultural revitalization focus',
      'Youth-elder connection'
    ],
    actionRequired: 'Research application process for Ashaninka cultural project',
    applyUrl: 'https://nativeland.org/mino-niibi-fund',
    sourceUrl: 'https://nativeland.org/mino-niibi-fund',
    tags: ['indigenous', 'cultural', 'foodways', 'peru'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'seventh-generation-fund',
    name: 'Seventh Generation Fund',
    region: 'pe',
    category: 'nfp',
    grantCategory: 'indigenous',
    amount: { min: 5000, max: 50000, display: 'Varies' },
    deadline: 'rolling',
    deadlineDisplay: 'Rolling',
    urgency: 'medium',
    entityType: 'Indigenous Community',
    description: 'Indigenous-led environmental and social justice.',
    whySacredFits: 'EXCELLENT - Ashaninka environmental stewardship, traditional knowledge.',
    eligibility: [
      'Indigenous-led initiative',
      'Environmental or social justice focus',
      'Community self-determination',
      'Traditional knowledge protection'
    ],
    actionRequired: 'Explore connection to Ashaninka environmental stewardship',
    applyUrl: 'https://7genfund.org',
    sourceUrl: 'https://7genfund.org',
    tags: ['indigenous', 'environmental', 'social-justice', 'peru'],
    addedDate: '2026-01-28',
    isNew: true
  },
  {
    id: 'iaf-grant',
    name: 'Inter-American Foundation (IAF)',
    region: 'pe',
    category: 'nfp',
    grantCategory: 'indigenous',
    amount: { min: 25000, max: 400000, display: '$25K-$400K' },
    deadline: 'rolling',
    deadlineDisplay: 'Rolling',
    urgency: 'high',
    entityType: 'NFP/Community',
    description: 'US government foundation supporting grassroots development in Latin America. Strong focus on indigenous communities and cacao!',
    whySacredFits: 'PERFECT - IAF specifically funds cacao community projects and has history with Ashaninka. Sacred\'s partnership is ideal.',
    eligibility: [
      'Latin American grassroots organisation',
      'Community-led development',
      'Sustainable livelihoods focus',
      'Can be supported by international partner'
    ],
    actionRequired: 'PRIORITY - Research IAF application process, potentially apply via Ashaninka cooperative',
    applyUrl: 'https://iaf.gov/apply-for-grant/',
    sourceUrl: 'https://iaf.gov/apply-for-grant/',
    tags: ['peru', 'indigenous', 'cacao', 'community', 'priority'],
    addedDate: '2026-01-23',
    isNew: true
  },
  {
    id: 'rainforest-trust',
    name: 'Rainforest Trust Grants',
    region: 'pe',
    category: 'nfp',
    grantCategory: 'environmental',
    amount: { min: 10000, max: 100000, display: '$10K-$100K' },
    deadline: 'rolling',
    deadlineDisplay: 'Rolling',
    urgency: 'medium',
    entityType: 'NFP/Community',
    description: 'Supports forest protection and indigenous land rights, particularly in the Amazon.',
    whySacredFits: 'Ashaninka territory protection and forest conservation aligns with Sacred\'s sourcing values.',
    eligibility: [
      'Forest/biodiversity conservation',
      'Indigenous land protection',
      'Community partnership',
      'Measurable conservation outcomes'
    ],
    actionRequired: 'Explore connection to Ashaninka land/forest protection',
    applyUrl: 'https://www.rainforesttrust.org/apply-for-a-grant/',
    sourceUrl: 'https://www.rainforesttrust.org/apply-for-a-grant/',
    tags: ['peru', 'amazon', 'indigenous', 'conservation'],
    addedDate: '2026-01-23',
    isNew: true
  },
  {
    id: 'nia-tero',
    name: 'Nia Tero Indigenous Guardianship',
    region: 'pe',
    category: 'nfp',
    grantCategory: 'indigenous',
    amount: { min: 50000, max: 500000, display: '$50K-$500K' },
    deadline: 'rolling',
    deadlineDisplay: 'By invitation/EOI',
    urgency: 'medium',
    entityType: 'Indigenous Community',
    description: 'Supports indigenous peoples to protect their lands and maintain traditional practices.',
    whySacredFits: 'Could support Ashaninka community\'s guardianship of territory and traditional cacao practices.',
    eligibility: [
      'Indigenous-led initiative',
      'Land/territory protection',
      'Cultural preservation',
      'Community self-determination'
    ],
    actionRequired: 'Research Nia Tero\'s approach and potential Ashaninka partnership',
    applyUrl: 'https://niatero.org/contact/',
    sourceUrl: 'https://niatero.org',
    tags: ['peru', 'indigenous', 'guardianship', 'large-grant'],
    addedDate: '2026-01-23',
    isNew: true
  },

  // 🌍 INTERNATIONAL
  {
    id: 'ashoka-fellowship',
    name: 'Ashoka Fellowship',
    region: 'int',
    category: 'individual',
    grantCategory: 'social-enterprise',
    amount: { min: 0, max: 0, display: 'Stipend + Network' },
    deadline: 'rolling',
    deadlineDisplay: 'Rolling (nomination)',
    urgency: 'low',
    entityType: 'Individual',
    description: 'World\'s largest network of social entrepreneurs. Fellows receive stipend and lifetime membership.',
    whySacredFits: 'Sacred founder could be nominated as social entrepreneur in ethical food/cultural space.',
    eligibility: [
      'Social entrepreneur with new idea',
      'System-changing approach',
      'Ethical fiber',
      'Nomination required'
    ],
    actionRequired: 'Research Ashoka nominator in Australia',
    applyUrl: 'https://www.ashoka.org/en-au/program/ashoka-fellowship',
    sourceUrl: 'https://www.ashoka.org',
    tags: ['international', 'social-entrepreneur', 'fellowship', 'network'],
    addedDate: '2026-01-01',
    isNew: false
  },
  {
    id: 'skoll-award',
    name: 'Skoll Award for Social Entrepreneurship',
    region: 'int',
    category: 'nfp',
    grantCategory: 'social-enterprise',
    amount: { min: 500000, max: 1500000, display: '$500K-$1.5M' },
    deadline: '2026-06-30',
    deadlineDisplay: '30 Jun 2026',
    urgency: 'low',
    entityType: 'NFP',
    description: 'Major award for proven social entrepreneurs driving large-scale change.',
    whySacredFits: 'Long-term goal as Sacred scales impact. Requires significant track record.',
    eligibility: [
      'Proven social entrepreneur',
      'Scalable model',
      '5+ years of impact',
      'Systems-level change'
    ],
    actionRequired: 'Track for future when Sacred has larger track record',
    applyUrl: 'https://skoll.org/about/skoll-awards/',
    sourceUrl: 'https://skoll.org',
    tags: ['international', 'social-entrepreneur', 'award', 'large-grant'],
    addedDate: '2026-01-01',
    isNew: false
  }
]

// Region definitions
export const regions = [
  { id: 'all', name: 'All Regions', flag: '🌐', count: grants.length },
  { id: 'au', name: 'Australia', flag: '🇦🇺', count: grants.filter(g => g.region === 'au').length },
  { id: 'nl', name: 'Netherlands', flag: '🇳🇱', count: grants.filter(g => g.region === 'nl').length },
  { id: 'eu', name: 'EU-wide', flag: '🇪🇺', count: grants.filter(g => g.region === 'eu').length },
  { id: 'pe', name: 'Peru/LatAm', flag: '🇵🇪', count: grants.filter(g => g.region === 'pe').length },
  { id: 'int', name: 'International', flag: '🌍', count: grants.filter(g => g.region === 'int').length },
]

// Categories for filtering
export const categories = [
  { id: 'all', name: 'All Grants', count: grants.length },
  { id: 'urgent', name: 'Urgent', count: grants.filter(g => g.urgency === 'urgent').length },
  { id: 'pty-ltd', name: 'Pty Ltd Eligible', count: grants.filter(g => g.category === 'pty-ltd').length },
  { id: 'nfp', name: 'NFP Required', count: grants.filter(g => g.category === 'nfp').length },
  { id: 'individual', name: 'Individual/Artist', count: grants.filter(g => g.category === 'individual').length },
  { id: 'nomination', name: 'Nomination', count: grants.filter(g => g.category === 'nomination').length },
]

// Grant categories (what the grant is for)
export const grantCategories = [
  { id: 'all', name: 'All Types' },
  { id: 'cultural', name: 'Cultural' },
  { id: 'arts', name: 'Arts' },
  { id: 'performing-arts', name: 'Performing Arts' },
  { id: 'health', name: 'Health/Wellbeing' },
  { id: 'social-enterprise', name: 'Social Enterprise' },
  { id: 'indigenous', name: 'Indigenous' },
  { id: 'food', name: 'Food/Agri' },
  { id: 'export', name: 'Export' },
  { id: 'environmental', name: 'Environmental' },
  { id: 'documentary', name: 'Documentary' },
  { id: 'education', name: 'Education' },
]

// Progress stages for tracking
export const progressStages = [
  { id: 'not-started', name: 'Not Started', color: 'gray' },
  { id: 'researching', name: 'Researching', color: 'blue' },
  { id: 'drafting', name: 'Preparing', color: 'yellow' },
  { id: 'submitted', name: 'Submitted', color: 'purple' },
  { id: 'awaiting', name: 'Awaiting', color: 'orange' },
  { id: 'successful', name: 'Won', color: 'green' },
  { id: 'unsuccessful', name: 'Lost', color: 'red' },
]

// Summary statistics - Updated with EU research data
export const summary = {
  totalGrants: grants.length,
  conservative: 1800000, // €1.8M conservative estimate
  optimistic: 35000000, // €35M+ potential (as per EU research doc)
  ptyLtdCount: grants.filter(g => g.category === 'pty-ltd').length,
  nfpCount: grants.filter(g => g.category === 'nfp').length,
  individualCount: grants.filter(g => g.category === 'individual').length,
  urgentCount: grants.filter(g => g.urgency === 'urgent').length,
  newCount: grants.filter(g => g.isNew).length,
  euPotential: 30000000, // €30M+ EU funding potential
  nlPotential: 8000000, // €8M+ Netherlands private foundations
}

// Grant sources for scraping - Comprehensive list from EU research
export const grantSources = {
  australia: [
    { name: 'business.gov.au', url: 'https://business.gov.au/grants-and-programs', type: 'rss' },
    { name: 'GrantConnect', url: 'https://www.grants.gov.au/', type: 'scrape' },
    { name: 'Austrade', url: 'https://www.austrade.gov.au/en/how-we-can-help-you/grants-funding-assistance', type: 'scrape' },
    { name: 'Creative Australia', url: 'https://creative.australia.gov.au/funding', type: 'scrape' },
    { name: 'Screen Australia', url: 'https://www.screenaustralia.gov.au/funding', type: 'scrape' },
    { name: 'Business Victoria', url: 'https://business.vic.gov.au/grants-and-programs', type: 'scrape' },
    { name: 'City of Melbourne', url: 'https://www.melbourne.vic.gov.au/community/grants-and-sponsorships', type: 'scrape' },
  ],
  netherlands: [
    // Six National Cultural Funds (Rijkscultuurfondsen)
    { name: 'Fonds Podiumkunsten', url: 'https://fondspodiumkunsten.nl/en/', type: 'scrape' },
    { name: 'Mondriaan Fund', url: 'https://www.mondriaanfonds.nl/en/', type: 'scrape' },
    { name: 'Fonds voor Cultuurparticipatie', url: 'https://cultuurparticipatie.nl', type: 'scrape' },
    { name: 'Stimuleringsfonds', url: 'https://stimuleringsfonds.nl/en/', type: 'scrape' },
    { name: 'Netherlands Film Fund', url: 'https://filmfonds.nl', type: 'scrape' },
    { name: 'Dutch Foundation for Literature', url: 'https://letterenfonds.nl', type: 'scrape' },
    // Major Lottery-Connected Funds
    { name: 'DOEN Foundation', url: 'https://www.doen.nl/en', type: 'scrape' },
    { name: 'Oranjefonds', url: 'https://oranjefonds.nl', type: 'scrape' },
    { name: 'Prins Bernhard Cultuurfonds', url: 'https://www.cultuurfonds.nl/en', type: 'scrape' },
    // Independent Dutch Foundations
    { name: 'Triodos Foundation', url: 'https://triodos.com/regenerative-money-centre', type: 'scrape' },
    { name: 'Dioraphte Foundation', url: 'https://dioraphte.nl', type: 'scrape' },
    { name: 'Fonds 21', url: 'https://fonds21.nl', type: 'scrape' },
    { name: 'VSBfonds', url: 'https://vsbfonds.nl', type: 'scrape' },
    { name: 'KansFonds', url: 'https://kansfonds.nl', type: 'scrape' },
    // Social Enterprise
    { name: 'Social Enterprise NL', url: 'https://social-enterprise.nl/english', type: 'scrape' },
    { name: 'Start Foundation', url: 'https://startfoundation.nl', type: 'scrape' },
  ],
  eu: [
    { name: 'Creative Europe', url: 'https://culture.ec.europa.eu/creative-europe', type: 'scrape' },
    { name: 'EU Funding Portal', url: 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/', type: 'api' },
    { name: 'European Cultural Foundation', url: 'https://culturalfoundation.eu', type: 'scrape' },
    { name: 'Culture Moves Europe', url: 'https://culture.ec.europa.eu/creative-europe/culture-moves-europe', type: 'scrape' },
    { name: 'EFFEA', url: 'https://effea.eu', type: 'scrape' },
    { name: 'EIT Culture & Creativity', url: 'https://eit-culture-creativity.eu', type: 'scrape' },
    { name: 'EU4Health', url: 'https://hadea.ec.europa.eu/programmes/eu4health', type: 'scrape' },
    { name: 'CERV', url: 'https://commission.europa.eu/funding-tenders', type: 'api' },
    { name: 'Erasmus+', url: 'https://erasmus-plus.ec.europa.eu', type: 'scrape' },
    // Interreg Programs
    { name: 'Interreg NWE', url: 'https://nweurope.eu', type: 'scrape' },
    { name: 'Interreg North Sea', url: 'https://northsearegion.eu', type: 'scrape' },
    { name: 'Interreg Meuse-Rhine', url: 'https://interregmeuserhine.eu', type: 'scrape' },
  ],
  peru: [
    { name: 'Inter-American Foundation', url: 'https://iaf.gov/apply-for-grant/', type: 'scrape' },
    { name: 'Rainforest Trust', url: 'https://www.rainforesttrust.org/apply-for-a-grant/', type: 'scrape' },
    { name: 'Prince Claus Fund', url: 'https://princeclausfund.org', type: 'scrape' },
    { name: 'Cultural Survival', url: 'https://culturalsurvival.org/grantmaking', type: 'scrape' },
    { name: 'Seventh Generation Fund', url: 'https://7genfund.org', type: 'scrape' },
  ],
  international: [
    { name: 'Funds for NGOs', url: 'https://www2.fundsforngos.org', type: 'scrape' },
    { name: 'Ashoka', url: 'https://www.ashoka.org', type: 'scrape' },
    { name: 'Skoll Foundation', url: 'https://skoll.org', type: 'scrape' },
  ]
}
